### ISSUE TITLE
(GSSoC'24) Enhancements and Fixes for Login Page UI and Profile Photo Changing Functionality

### ISSUE THREAD

**Issue by Apurv7777** [harshalhonde21/EcommerceSpectastyle#10]
**Login Page UI Issues:**

- Issue: The login page UI is not visually appealing and lacks consistency with the overall design.

- Details: Elements such as buttons, input fields, and layout need refinement to enhance user experience.

- Expected Behavior: The login page should have a polished appearance that aligns with the app's design language.

- Priority: Medium

**Profile Photo Chanigng Functionality:**

- Feature Request: Integrate the ability for users to edit and change their profile photos within the app.

- Description: Users should have the option to upload, crop, and adjust their profile photos directly from their account settings.

- Expected Behavior: Upon selecting the profile photo section, users should be able to upload an image, crop it if necessary, and save the changes.

- Priority: High

> Please feel free to provide additional details or suggestions. Contributions and feedback are welcome!

Assignees: Assigned me this issue.

**Comment by harshalhonde21** [comment]
@Apurv7777, basically this issue is very good to solve, but basically what i want see the signup and login page enhance the UI of that and it has some bugs just take output update me that all with proper images I will assign this issue to you.

Don't forgot to star the repo

**Comment by Apurv7777** [comment]
### Here, When I clicked on show password icon, the input field collapsed.
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/65327303/c5b86239-955a-4e4f-8acc-726ddfbbc2aa)

### In the input fields, the icon of email and visibility are mis-aligned.
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/65327303/52b0e824-6496-4195-b7dc-b8d886004120)

**Comment by harshalhonde21** [comment]
Do with this and raise the PR, I will check and if good to see that nice, I am assigning this issue to you.
