### ISSUE TITLE
Improving overall look of UI and adding dark mode 

### ISSUE THREAD

**Issue by AishMishra001** [harshalhonde21/EcommerceSpectastyle#106]
The current website ui and colour combination looks very weird and basic and this leads to a poor client experience so as I am a contributor in GSSoC 2024 I would like to contribute and make the UI better and add dark light mode toggle . 

Please assign me this issue under GSSoC 2024 contributor .

**Comment by harshalhonde21** [comment]
good @AishMishra001 check first how the issue or feature is been created then come up with another correct issue see the folder [.github/ISSUE_TEMPLATE](https://github.com/harshalhonde21/EcommerceSpectastyle/tree/main/.github/ISSUE_TEMPLATE)

**Comment by AishMishra001** [comment]
Hi @harshalhonde21 sorry I am extremely new to open source and didn't know the proper format of create an issue . 
I am looking forward for further guidance from you ... 

for now can u please tell me is the feature or changes I suggest isn't good enough orr isn't required current orr anything in particular you can tell me . 

also as a newbie in open source I find most of the issue in any good project is already assigned .....what should i do ??
