### ISSUE TITLE
Navbar's elements and hover effect is not according to the principles of UI/UX.

### ISSUE THREAD

**Issue by shnwz-solves** [harshalhonde21/EcommerceSpectastyle#107]
The navbar menu is not following principles of UI/UX, hover effect and text decoration also need to be fixed.

![Screenshot 2024-05-12 111943](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/126380641/3e6ffc7b-1ab6-43ef-a1c1-bf7446e269f5)

Hey PA, I want to contribute, please assign this issue to me. Thankyou!

**Comment by harshalhonde21** [comment]
take the pull then check
