### ISSUE TITLE
Improving the UI and semantics of About section

### ISSUE THREAD

**Issue by AnandK-pm** [harshalhonde21/EcommerceSpectastyle#108]
### Describe the feature

Currently the about section looks so out of place when compared to other p[arts of the website and also have some semantical errors ( Ex : spelling of delivery ). Please assign me this task so that i can work on this issue thereby making the about section a little more tidy and exquisite.

### Add ScreenShots

![Screenshot 2024-05-12 111815](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/142206618/52dc061f-fa5b-4b46-ab3b-70f85583ab23)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
No need of this
