### ISSUE TITLE
Addd follow us on LinkedIn button 

### ISSUE THREAD

**Issue by rajlaxmi03** [harshalhonde21/EcommerceSpectastyle#115]
### Describe the feature

Addd follow us on LinkedIn button 

### Add ScreenShots

Addd follow us on LinkedIn button 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
Always follow the template of issue creatio,
