### ISSUE TITLE
Feat:Add contact us page 

### ISSUE THREAD

**Issue by rajlaxmi03** [harshalhonde21/EcommerceSpectastyle#116]
### Describe the feature

Add contact us page and enhance that 

### Add ScreenShots

Add contact us page 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tyagismriti** [comment]
I want to work on this issue please assigned me this task under GSSOC 24

**Comment by harshalhonde21** [comment]
Already is there
