### ISSUE TITLE
Feat: enhance the navbar 

### ISSUE THREAD

**Issue by Harshitazz** [harshalhonde21/EcommerceSpectastyle#120]
### Describe the feature

decrease width and add effects to links

### Add ScreenShots

![Screenshot 2024-05-12 122914](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/118474653/9e60f158-35ff-43fc-bd23-2e4367335d62)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
You are using old version take the pull
