### ISSUE TITLE
BUG: The navbar is hiding some of the hero section in small devices.

### ISSUE THREAD

**Issue by shnwz-solves** [harshalhonde21/EcommerceSpectastyle#121]
###The issue 
The issue is with the navbar and hero section. 
The navbar is hiding some of the hero section in small devices.

###To fix
I will change some styling of the navbar and hero section.

###Screenshot
[]()![Screenshot_2024-05-12-12-27-55-28_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/126380641/30974875-45bc-41f5-b83a-0edbdf80243a)

Hey PA, please assign this task to me. I would like to contribute. Thankyou!

**Comment by harshalhonde21** [comment]
Wrong format of issue
