### ISSUE TITLE
Feat: About page redesign

### ISSUE THREAD

**Issue by Harshitazz** [harshalhonde21/EcommerceSpectastyle#122]
### Describe the feature

the fonts are mismatched and the appeal is bad...

### Add ScreenShots

![Screenshot 2024-05-12 123049](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/118474653/74aa7b81-10c5-4cc8-83ee-8fa6b2737f8d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
No need of this
