### ISSUE TITLE
Feat: adding favicon icon 

### ISSUE THREAD

**Issue by solanki505** [harshalhonde21/EcommerceSpectastyle#125]
### Describe the feature

I will add the favicon icon using html

### Add ScreenShots

![Screenshot 2024-05-12 131923](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/158484284/d2cfea6a-462d-47d5-955c-0905cc5b2de7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AshishKumarSamantaray** [comment]
please assign me for this as i can create a subtle temporary logo and move forward with this

**Comment by harshalhonde21** [comment]
Go with this

**Comment by AshishKumarSamantaray** [comment]
> Go with this

Assign me please sir
