### ISSUE TITLE
Adding Rating System 

### ISSUE THREAD

**Issue by StephenStolk** [harshalhonde21/EcommerceSpectastyle#128]
### Describe the feature

Users can rate the product in addition to review.

### Add ScreenShots

![Screenshot_2024-05-12-14-20-31-64_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/134587780/e408a7a7-154e-4542-8ddd-70485e16104e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by StephenStolk** [comment]
I want to take up this issue.

**Comment by harshalhonde21** [comment]
This updated is not nessary because there is already the review comment
