### ISSUE TITLE
hidden buttons in mobile view

### ISSUE THREAD

**Issue by dev04sa** [harshalhonde21/EcommerceSpectastyle#129]
@harshalhonde21 as you can see , In mobile view products and about us buttons are hidden due to overflow.
I want to solve this issue , kindly assign it to me.
![Screenshot 2024-05-12 151252](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/129666293/d6985082-7b2a-49ac-8777-f90caf0c2d34)

**Comment by harshalhonde21** [comment]
Issue format is incorrect
