### ISSUE TITLE
Opening Section Updation

### ISSUE THREAD

**Issue by AshishKumarSamantaray** [harshalhonde21/EcommerceSpectastyle#130]
**UPDATE THE OPENING WEB PAGE**

The front or the opening page of this website can be improved. The topic is excellent for choosing a wide variety of designs so we can work on it please assign me so that i can move forward with the implementation of my designs

### Add ScreenShots

![SPECTASTYLE - Brave 5_12_2024 3_28_29 PM](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/121350516/b4a78d36-5c94-4bb2-9807-3825e99c75ea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
Already listen in #131 go there

**Comment by AshishKumarSamantaray** [comment]
Please assign me
