### ISSUE TITLE
On entering undefined routes showing unwanted behaviour .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [harshalhonde21/EcommerceSpectastyle#136]
### Describe the feature

By entering undefined path (Any path ) to the route then it moves on unwanted page with wrong css .

Steps to reproduce :-
1. GO to Website and enter any unwanted path like (https://spectastyle.vercel.app/sasas) .
2. You will see a page with no content and with wrong css .

### Add ScreenShots

![Screenshot 2024-05-12 202126](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/118350936/93e78a35-834f-487b-8577-5df1e510dea7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/105191619/29dad227-9cf4-48c3-af04-16bcb1e7f252)


come up with great more issue
