### ISSUE TITLE
Feat:Adding E-mail Validation

### ISSUE THREAD

**Issue by keshavsinha17** [harshalhonde21/EcommerceSpectastyle#137]
### Describe the feature

I was able to sign up for the website using a dummy email which isn't a valid email. this leads to spam and fake accounts on websites.
Here are the 2 approaches I  can propose for resolving the same:-
1) Handling Login Signup using OAuth.
2) Implementing a mail-based pin matching using node-mailer(a bit messy solution).
I can try and solve using both methods, however I would suggest going with oAuth.
if you can assign this to me under gssoc I can give it a shot .!!

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123925652/c783ae31-928d-4007-b593-314556b6fa59)

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123925652/62d8c157-9703-4601-a56c-0d1cd4183ab6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
Already solving in another PR
