### ISSUE TITLE
Feat:Better Error Messages for Signup Form

### ISSUE THREAD

**Issue by keshavsinha17** [harshalhonde21/EcommerceSpectastyle#138]
### Describe the feature

When you fill the signup form ,if any field is missing or incorrect a toast pops up however it's message ain't clear leaving user to think on it's own.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123925652/0aeb5f56-aacb-415b-96d8-e0eea86e3a69)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by keshavsinha17** [comment]
can you assign this to me under gsoc

**Comment by harshalhonde21** [comment]
There is proper messages which is coming from backend no need to do error handling in frontend
