### ISSUE TITLE
Feat: Redesign About Page for Enhanced Engagement

### ISSUE THREAD

**Issue by KARANSINGH34951** [harshalhonde21/EcommerceSpectastyle#143]
### Describe the feature

I've noticed that our About page currently appears too basic and static, which may not effectively engage to audience or convey our brand's story and values. I propose redesigning the About page to create a more dynamic and compelling experience .

### Add ScreenShots

<img width="960" alt="Screenshot 2024-05-13 010546" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/137412876/d801a94e-1632-4567-8f02-761e81eba907">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
No need of this else redesign the home page
