### ISSUE TITLE
Redundant Name entry in Contact Form

### ISSUE THREAD

**Issue by SamarthUrane** [harshalhonde21/EcommerceSpectastyle#146]
The contact form currently prompts users to input their name twice, both labeled as 'Good Name.' This redundancy can confuse users. I've resolved this issue to streamline the form for better user experience. 
Please assign this enhancement under GSSOC. Thank you.

![Screenshot 2024-05-13 025255](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/108013711/e85bca5a-ad37-4645-a960-48d3ad7a6396)

**Comment by abhiperfect** [comment]
Subject: Redundant Name entry in Contact Form 

Hi @harshalhonde21 ,

I respectfully request assignment of the task to address the duplicate "good name" issue in the Contact Form. Your guidance in resolving this matter efficiently would be greatly appreciated.

Thank you,
Abhishek

**Comment by harshalhonde21** [comment]
Already solving in another issue
