### ISSUE TITLE
BUG : Footer text is overlapping

### ISSUE THREAD

**Issue by Apoorva-Rajput** [harshalhonde21/EcommerceSpectastyle#147]
### Describe the feature

The text in footer is overlapping and seems inconsistent .
@harshalhonde21 kindly allow me to work on this issue under GSSoC'24 contribution .

### Add ScreenShots

![Screenshot (323)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/98842014/3e018824-8f0b-4ee3-8081-671d99e73f13)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
great do with this
