### ISSUE TITLE
Improve the Responsiveness of the website

### ISSUE THREAD

**Issue by ekkaaditya200** [harshalhonde21/EcommerceSpectastyle#148]
### What's wrong with the existing documentation

The header is not responsive, and SPECTASTYLE text is getting overlapped with the header.

### Add ScreenShots

![SPECTASTYLE](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/101588644/28d1eb26-32a0-4017-8774-975b8a43983d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ekkaaditya200** [comment]
I can fix the this issue you can assign it to me. Also add GSSOC and level labels.

**Comment by harshalhonde21** [comment]
Already doing in another issue
