### ISSUE TITLE
[UI] : Responsiveness issue in About.jsx

### ISSUE THREAD

**Issue by SaranshBangar** [harshalhonde21/EcommerceSpectastyle#15]
The [About](https://spectastyle.vercel.app/about) page of the website has overlapping text from 500px to 905px screen width. This could have a significant impact on users opening the website on a tablet

Images ->

500px - 
![WhatsApp Image 2024-05-10 at 08 19 55_bb988e75](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/114401238/5917e500-3490-421d-bbcb-9fd61703928f)

905px -
![WhatsApp Image 2024-05-10 at 08 20 18_2add5d3e](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/114401238/08e275d1-e674-4095-8212-b25b41e62333)

Request - Please assign the issue to me, I am a contributor in GSSoC

**Comment by harshalhonde21** [comment]
> The [About](https://spectastyle.vercel.app/about) page of the website has overlapping text from 500px to 905px screen width. This could have a significant impact on users opening the website on a tablet
> 
> Images ->
> 
> 500px - ![WhatsApp Image 2024-05-10 at 08 19 55_bb988e75](https://private-user-images.githubusercontent.com/114401238/329441783-5917e500-3490-421d-bbcb-9fd61703928f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjEzODMsIm5iZiI6MTcxNTMyMTA4MywicGF0aCI6Ii8xMTQ0MDEyMzgvMzI5NDQxNzgzLTU5MTdlNTAwLTM0OTAtNDIxZC1iYmNiLTlmZDYxNzAzOTI4Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwNjA0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmQ1Mzg4ZjcwZjU1ZjBlOTk4YTM3OWNkMWNhZjQzMTYyYzVjNDhjZjNiMjIwM2I1ZTVjNmViZWM4ZWM5MGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OCXUhDczvIFqAkXSbfzfQi8AsBhMvM2l0LPHgRbrfIE)
> 
> 905px - ![WhatsApp Image 2024-05-10 at 08 20 18_2add5d3e](https://private-user-images.githubusercontent.com/114401238/329441820-08e275d1-e674-4095-8212-b25b41e62333.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjEzODMsIm5iZiI6MTcxNTMyMTA4MywicGF0aCI6Ii8xMTQ0MDEyMzgvMzI5NDQxODIwLTA4ZTI3NWQxLWU2NzQtNDA5NS04MjEyLWIyNWI0MWU2MjMzMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwNjA0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDMwNTZhNWRjZDA4NTI3NTljMTdmYWNkZDFmYTQwYWUzZjAwZjVlN2YwOTNhMjA5ZDJmMTg4NjFmODQwYWM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ih5OH1n9JcYqYSOR6NNxw2NAcSBiW1ktX9uHSWqwmJA)
> 
> Request - Please assign the issue to me, I am a contributor in GSSoC

Great thought @SaranshBangar do with this and raise the PR.

**Comment by git-akhi3** [comment]
Hey please assign me this issue, i am a frontend developer with proficiency in react js and UI enhancement

**Comment by harshalhonde21** [comment]
> Hey please assign me this issue, i am a frontend developer with proficiency in react js and UI enhancement

Great do with this.

**Comment by SaranshBangar** [comment]
Resolved in PR #22
