### ISSUE TITLE
UI of signin and signup page is not good and  it is very simple 

### ISSUE THREAD

**Issue by mihirpatel07a** [harshalhonde21/EcommerceSpectastyle#152]
### Describe the feature

i can create very impressive sign in and sign up page usigng tailwind css which is fully responsive so please assign this issue to me @harshalhonde21 

### Add ScreenShots

![Screenshot (483)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/105737077/7b2584fb-655f-4762-9ff3-4a6d99d6a2e4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
It is matching with theme and I want current only

**Comment by mihirpatel07a** [comment]
Ok 👍
