### ISSUE TITLE
[Bug] : Button are not accessable

### ISSUE THREAD

**Issue by sivaprasath2004** [harshalhonde21/EcommerceSpectastyle#154]
### What's wrong with the existing documentation

- The login and signup toggle button cannot `pointing` .
- User that is letter or something not `clickable` area.

### Add ScreenShots

![Screenshot from 2024-05-13 17-41-09](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/121082414/a08a481d-60d9-4167-8f6c-8879533d360b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
It is accessable go and check once again
