### ISSUE TITLE
DOC:

### ISSUE THREAD

**Issue by Chitransh-j** [harshalhonde21/EcommerceSpectastyle#156]
### Add ScreenShots

<img width="614" alt="app_design" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/135858715/24f93fde-ab42-49fb-9535-dd4cf17c8c79">

---

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
Great, the PR you will great is get revied correctly so do it perfectly
