### ISSUE TITLE
User Visits is not align in navbar

### ISSUE THREAD

**Issue by Shivam-fibo** [harshalhonde21/EcommerceSpectastyle#157]
In Main page under the navbar section the user visit is not proper align 
**Add ScreenShots**
![Screenshot 2024-05-13 180203](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115231608/f9e98820-1ae5-493f-be76-c50fa38d7bae)

**Comment by harshalhonde21** [comment]
You have zoom that extra there it is showing like that do with 100x only
