### ISSUE TITLE
Feature: Redirect to Dialer pad, Email-box and Google Map

### ISSUE THREAD

**Issue by pankaj-bind** [harshalhonde21/EcommerceSpectastyle#161]
### Describe the feature

When user click on 
phone number redirects to dialer pad
email redirects to email box
address redirect to google map on the given location

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/73558583/7f9265dd-02b1-4f44-8393-c9fdefb131f3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
No need of this as it is dummy and I need that part to dummy only
