### ISSUE TITLE
Feat:Responsiveness errror

### ISSUE THREAD

**Issue by Mehulsingh1010** [harshalhonde21/EcommerceSpectastyle#163]
### Describe the feature

When using the mobile view in inspect element, navbar is overlapping homepage content. I can fix it

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/137038233/79464b9c-79dd-4b37-9041-c18a1f5f5a2d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
Already #172 is doing this
