### ISSUE TITLE
Feat: Mouse Transition Effect

### ISSUE THREAD

**Issue by MitulSonagara** [harshalhonde21/EcommerceSpectastyle#167]
### Describe the feature

As your websites looks very futuristic and beautiful it will enhance the looks of the website. I will do it like mouse cursor with trailing effect.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/95460188/2c083073-25fd-4552-90d4-b1bcfd5b0c07)

It will like where ever the cursor goes this circle will follow the cursor.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
No need of this I already done the update but the website been slow
