### ISSUE TITLE
Feat: Home page not view properly in mobile view

### ISSUE THREAD

**Issue by kapilG0** [harshalhonde21/EcommerceSpectastyle#172]
### Describe the feature

Content is not displaying properly in mobile view 

### Add ScreenShots

![Screenshot_20240514_153454](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/59639410/fede0514-2896-4598-a8cf-3b0d7f9c2938)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
Great @kapilG0  go with this

**Comment by kapilG0** [comment]
Hello @harshalhonde21 i am closing this it is fixed by some else and working fine in local. Thanks
