### ISSUE TITLE
Feat: Need to add validation for email 

### ISSUE THREAD

**Issue by kapilG0** [harshalhonde21/EcommerceSpectastyle#173]
### Describe the feature

Validation required 

### Add ScreenShots

![Screenshot_20240514_154002](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/59639410/11ae21b3-af83-468d-9344-e79f617acdab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @harshalhonde21 i request if you find that it is issue please assign to me under gssoc

**Comment by harshalhonde21** [comment]
As said in your previous issue no need of the validation to the contact form if you want to contribute design the HOme page
