### ISSUE TITLE
Feat: Need to add validation for phone number in contact form

### ISSUE THREAD

**Issue by kapilG0** [harshalhonde21/EcommerceSpectastyle#174]
### Describe the feature

I filled only 1 in phone number and form was submitted but it should give error

### Add ScreenShots

![Screenshot_20240514_154321](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/59639410/3c01ff6b-ebf4-474e-a5b6-4af5d91903a2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
There is no need of validation of phone number because it is dummy form there is not a backend funtionality
