### ISSUE TITLE
Bug:Syntax issue in bug issue template

### ISSUE THREAD

**Issue by Niharika0104** [harshalhonde21/EcommerceSpectastyle#175]
I saw that there is a syntax error in the bug issue template.I would like to fix that.
<img width="908" alt="bugissue" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/124892559/bed04922-e75d-4cdb-b5f7-cade37e5112a">

**Comment by harshalhonde21** [comment]
You can contribute great
