### ISSUE TITLE
Improving the Products Page search bar & content

### ISSUE THREAD

**Issue by riya-rjha** [harshalhonde21/EcommerceSpectastyle#177]
### Describe the feature

When clicked on the search bar in the products page, it creates an outline over the body of the container which is not an enhanced feature. Plus the text, in status does not fit well here. It would be better if changed to "In Stock". 

### Add ScreenShots

![Screenshot (562)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/112813772/ab5fdc1a-2f5b-4394-b3a9-5b8a0a53ecb5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by riya-rjha** [comment]
Thanks for assigning me this issue! Surely will start working rightaway

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.
