### ISSUE TITLE
Login & SignUp form visibility on smaller screens (or zoomed in screens)

### ISSUE THREAD

**Issue by riya-rjha** [harshalhonde21/EcommerceSpectastyle#178]
### Describe the feature

When zoomed by 150% on desktops, or when on mobile screens, both the login & signup forms overlap with the navigation bar. Also the content in the login form that if you are an existing user, please sign up looks very dull. I would prefer to add an underline over signup, make it in italics & sort of change it's color. If assigned to me, I would use tailwind CSS to work on this.

### Add ScreenShots

![Screenshot (563)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/112813772/16759e91-20f8-45f5-bb17-de5d1a20955a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
There is no need to zoom the website and in mobile there is no problem with the page visible 

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/105191619/828202db-9a18-41e7-8bba-6db0e2c3d30e)


check with this SS

For current the PR is not satisfied therefore it is close
