### ISSUE TITLE
Reset password and Change photo are not implemented

### ISSUE THREAD

**Issue by Nikhilesh002** [harshalhonde21/EcommerceSpectastyle#183]
### Describe the feature

Reset password and Change photo are not implemented in userprofile section and also instead of profile photo, logo is shown there. 

I want to work on this feature. @harshalhonde21 Please assign me this task with required labels for gssoc24.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/134734453/9b6f31f3-9600-47f5-a6a7-0e71c6c1b7f5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
As because there is no backend functionality and any other contriubtor are doing work on that 

hence for that reason the issue is delected
