### ISSUE TITLE
feat: Download Links Not Redirecting to Download Page

### ISSUE THREAD

**Issue by soumojeet-mondal** [harshalhonde21/EcommerceSpectastyle#190]
### Describe the feature

In the "Home page" section of the website, under the "Links" category, the "Download for Mac" and "Download for Windows" options are provided for users to download our app for their respective platforms. However, clicking on these links does not redirect users to the download page where they can download the app.

**Expected Behavior:**
When users click on the "Download for Mac" or "Download for Windows" links, they should be redirected to the download page, where they can initiate the download process for the app compatible with their platform.

**Steps to Reproduce:**

    1) Navigate to the "Home page" section of the website.
    2) Locate the "Links" category.
    3) Click on the "Download for Mac" or "Download for Windows" link.
    4) Observe that the page does not redirect to the download page as expected.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/157923320/ecd939b8-7d02-49a9-93ca-1acbfb3cca28)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by abhiperfect** [comment]
I can work on this issue, but first, I'd like to know to which location these links will redirect.
