### ISSUE TITLE
Improving Remove From Cart Functionality

### ISSUE THREAD

**Issue by UjjwalGupta1105** [harshalhonde21/EcommerceSpectastyle#195]
### What's wrong with the existing documentation

When user is removing a product from the cart , then the user is directly thrown into the main page.
I want to resolve the issue .

### Add ScreenShots

![newest](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/165131091/4bfdf9cf-a51d-4dbc-85d8-eb6b90db6888)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
already in another issue
