### ISSUE TITLE
Feat: Add Login & SignUp feature

### ISSUE THREAD

**Issue by omneaa** [harshalhonde21/EcommerceSpectastyle#196]
### Describe the feature

i suggest adding new feature , the feature is LogIn and signUp 
i can make the server side 
plz assign to me this task am GSSoC'24 contributer 

### Add ScreenShots

'

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
Already done this in past check the whole website then comeup with the features
