### ISSUE TITLE
Feat: Add order summary in the place order page

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [harshalhonde21/EcommerceSpectastyle#201]
### Describe the feature

In the place order page, it could be more engaging and user satisfication, if we display the order summary and edit cart button. 

### Add ScreenShots

current scenario: 
![Screenshot 2024-05-15 101914](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/139672976/ad0091d7-718d-40ae-8f89-28fb8aa1fd50)

my suggestion: 

![checkout](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/139672976/c575a92d-10ca-447b-a5a3-e66beed8f7d3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DharshiBalasubramaniyam** [comment]
Hi @harshalhonde21, please assign this issue to me

**Comment by harshalhonde21** [comment]
already included in website just see the website then come up with issue
