### ISSUE TITLE
Feat: Reset password frontend and backend

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [harshalhonde21/EcommerceSpectastyle#202]
### Describe the feature

frontend: 
1. Create a new file ResetPassword.jsx under pages folder
2. Create the ui
3. create a function for call the backend api

backend:
1. Add a new route for reset password in user-routes.js file
5. In user controller create a function for reset password. (If the current password is correct save the new password, else return a bad request message)

### Add ScreenShots

Sample ui:

![reset password](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/139672976/c6d5ec01-848e-4b7e-ab45-d0ea5f03908c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DharshiBalasubramaniyam** [comment]
Hi @harshalhonde21 , please assign this issue to me

**Comment by harshalhonde21** [comment]
already doing
