### ISSUE TITLE
Feat: Same product adding multiple times in the cart

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [harshalhonde21/EcommerceSpectastyle#203]
### Describe the feature

If user mistakenly clicked on the add to cart button of an item, which is already presented in the cart, The same item quantity should be increment. But in current scenario the item is added to the list as a new item each time when user add to cart. This is not a better user experience. 
One solution is incrementing the same item's quantity. Another one is displaying a warning message says that 'The item is already in the cart'.

Please assign this issue to me to solve this issue.

### Add ScreenShots

Current scnario: 
![Screenshot 2024-05-15 105607](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/139672976/68617019-aebf-4a98-826d-31af977dd06e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by DharshiBalasubramaniyam** [comment]
Hi @harshalhonde21 , please assign this issue to me

**Comment by harshalhonde21** [comment]
Great feature by the way we can go with this @DharshiBalasubramaniyam do with this

**Comment by DharshiBalasubramaniyam** [comment]
Thank you @harshalhonde21 sir for assigning me.

**Comment by Sandeep3jarma** [comment]
If user mistakenly clicked on the add to cart button of an item, which is already presented in the cart, The same item quantity should be increment. But in current scenario the item is added to the list as a new item each time when user add to cart. This is not a better user experience.
One solution is incrementing the same item's quantity. Another one is displaying a warning message says that 'The item is already in the cart'.

Please assign this issue to me to solve this issue.

**Comment by harshalhonde21** [comment]
closed as complete but not need of this because the code is incorrectly and the whole website is crashed for 10 mins need 20 mins to solve the problem
