### ISSUE TITLE
Feat: Inappropriate colour combination

### ISSUE THREAD

**Issue by yugal1107** [harshalhonde21/EcommerceSpectastyle#204]
### Describe the feature

As a user, I noticed that the color combination used on the website is not visually appealing and may impact user experience. The current colors might cause readability issues, accessibility problems, or discomfort for certain users. A white background will give a premium and attractive look to website.
This will build a trust in users.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/119532503/0caeba13-439c-40b7-a99e-b4e052efc205)

Here is example of white themed website.

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/119532503/48ae75ba-ac69-4f6c-850e-61d2523e7243)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by yugal1107** [comment]
Please assign this issue to me and give under gssoc give appropriate label

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by harshalhonde21** [comment]
Sorry to say but don't need this update because the color combination is correct because I am this color palette only and I don't need to change in color thankyou for the feature
