### ISSUE TITLE
Feat: Order Tracking feature

### ISSUE THREAD

**Issue by Chelseasingla1** [harshalhonde21/EcommerceSpectastyle#205]
### Describe the feature

I would like to add a feature where one can track their order status after making orders along with display of map

### Add ScreenShots

Like this:
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/129886894/23c43fd4-772b-47b2-a6f3-6967ee0fc078)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chelseasingla1** [comment]
Please assign me this issue under GSSoC'24.

**Comment by harshalhonde21** [comment]
How will you do that explain

**Comment by harshalhonde21** [comment]
After order and payment done there is noting happens as it is not real ecommerce no need of this
