### ISSUE TITLE
bug : In Mobile View Products Card is Not Responsive

### ISSUE THREAD

**Issue by Puskar-Roy** [harshalhonde21/EcommerceSpectastyle#21]
![productcard](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/113108193/3652dcc0-d5e8-4c93-b781-f5dac38a5002)

Issue: In Mobile View Products Card is Not Responsive

## Description:
The products section in home is currently not responsive.

## Proposed Solution:
Investigate the current CSS styles and media queries related to the Product page. Make necessary adjustments to ensure that the Product pager is responsive and functions correctly on mobile devices.

**Comment by SaranshBangar** [comment]
The products are visible in mobile view though @Puskar-Roy

**Comment by harshalhonde21** [comment]
@Puskar-Roy the product cart is correctly responsive the margin around that is disturb

**Comment by harshalhonde21** [comment]
> @harshalhonde21 Sir, can I correct the margin?

This is very small updated you can go with issue 13 in issue secction
