### ISSUE TITLE
Feat: After select a particular product items is not aligning in a card properly

### ISSUE THREAD

**Issue by kapilG0** [harshalhonde21/EcommerceSpectastyle#211]
### Describe the feature

after select product details not coming in proper format

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/59639410/8a214b24-1d43-41f2-8cf9-6d1b48076e76)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @harshalhonde21 Please assign this issue to me under gssoc 24.

**Comment by Dhevamuthu** [comment]
I would like to work for this issue as I hope will definitely solve this issue.
can u please assign this task for me under GSSOC 2024

**Comment by harshalhonde21** [comment]
Great you can solve this issue @kapilG0

**Comment by kapilG0** [comment]
Hello @harshalhonde21 today I started worked on that issue after sync my repo but now I found it has already fixed . I do not know who has fixed as you have assigned this to me. 
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/59639410/927383e1-df5e-4a3c-93c4-42c3244ecf27)
same for the issue #172 i raised my pr but because of conflict you told me to raise new pr and at that time also i found it has fixed by some one else . Please help . I will thankful to you.

**Comment by kapilG0** [comment]
Hello @harshalhonde21 i am closing this issue please check the above comment .
Thanks
