### ISSUE TITLE
Feat: add codeql workflow for `javascript`

### ISSUE THREAD

**Issue by harmeetsingh11** [harshalhonde21/EcommerceSpectastyle#217]
### Describe the feature

The repository contains code in `javascript` , it does not have workflow for code scanning. 

### How would you like to see it implemented?

I aim to implement the CodeQL workflow to automate security checks. CodeQL, GitHub's code analysis engine, will identify vulnerabilities in the code and present the findings as code scanning alerts. This workflow will be activated for every push, commit, and pull request through GitHub Actions.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
Not required as mentor and project admin doing the same
