### ISSUE TITLE
Feat: Regarding Website animation

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [harshalhonde21/EcommerceSpectastyle#219]
### Describe the feature

Regarding Website animation like scrolling ,come and out etc

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/125277258/8d7df7bc-12b1-4203-b8be-687a1b17e595)
here and the total website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
As the website is all about ecommerce there is no need of animation and stuff
