### ISSUE TITLE
hover

### ISSUE THREAD

**Issue by aashkaaaaaa** [harshalhonde21/EcommerceSpectastyle#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

we can add hover for cart and improve header. please assign me this issue under GSSoC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not much description so it is closed
