### ISSUE TITLE
Bug: Increment/Decrement quantity in the cart is not persistent

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [harshalhonde21/EcommerceSpectastyle#223]
### Describe the feature

This issue is regarding updating the quantity of cart items mechanism. The quantity is successfully incremented/decremented. 

but the issue is When refreshing the page, the updated quantity is again changed to the initial quantity value.

The reason for this is in the code, it is updating the quantity in frontend only (cart state of cart context), not in the database. 

if we update the qty in the database by calling an Api, we can solve this issue.

### Add ScreenShots

https://github.com/harshalhonde21/EcommerceSpectastyle/assets/139672976/ca675fe6-0b3f-41ff-8978-be2e8e800c44

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
Great take the command you can make changes but it is backend work you should carefull to take the pull all time as you are doing code and the code should be in MVC model
