### ISSUE TITLE
BUG: Outdated Twitter Icon

### ISSUE THREAD

**Issue by shreyyq** [harshalhonde21/EcommerceSpectastyle#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Twitter logo in the website is the old one and outdated, and it needs to be updated with the new X logo.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
NO need of this because the icons are dummy so it not in use
