### ISSUE TITLE
BUG: Styling and responsiveness of footer

### ISSUE THREAD

**Issue by m3kvt** [harshalhonde21/EcommerceSpectastyle#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi @harshalhonde21 ,
I would like to remove the extra space in the right of the footer and align it to center. Also I would like to improve the readability in different devices and beautify the same.
![Screenshot 2024-05-16 191628](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/98379619/d742ce6c-bcf7-41f7-ba17-550f552a38f6)

Could you please assign me this issue?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
The footer is already correctly responsive this issue can't assign because of no need of the issue and this feature sorry for inconvience
