### ISSUE TITLE
Feat: Want to add Logo in navbar and Home page styling

### ISSUE THREAD

**Issue by ChaitanyaLonarkar** [harshalhonde21/EcommerceSpectastyle#233]
### Describe the feature

@harshalhonde21 I want to add Logo in navbar and some Home page CSS  styling to make the UI more attractive. Assign me this issue.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/110454138/a4d75283-5be7-4c61-a24a-231a4d5f9163)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
great @ChaitanyaLonarkar You can work on it

**Comment by harshalhonde21** [comment]
done as completed
