### ISSUE TITLE
Hover effect in Navigation Bar components

### ISSUE THREAD

**Issue by riya-rjha** [harshalhonde21/EcommerceSpectastyle#234]
### Describe the feature

The hover effect in navigation bar is about underline, but the line which appears under the a link is very far away and does not look good. I would want to work on this to make it look better. Kindly assign this to me under the GSSoC'24 label.

### Add ScreenShots

Now: 
![Screenshot (583)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/112813772/b363df0e-a9ce-405c-90ec-fd562d97b8a9)

After changes it will look like this: 

![Screenshot (582)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/112813772/fe77a4c4-de53-409e-9565-851863f0aebb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ARPITBAJPAI0098** [comment]
hello boss can you pls assign this issue to me i am having 1year of experience in Mern stack currently serving as the Technical Executive  of Sphnix largest techfest of Rajasthan under NIT jaipur

**Comment by harshalhonde21** [comment]
alreade there no need of this
