### ISSUE TITLE
catchy and visually appealing logo

### ISSUE THREAD

**Issue by patelkiran185** [harshalhonde21/EcommerceSpectastyle#238]
![Screenshot 2024-05-17 020622](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/138752385/b2a4b59e-90e5-491c-8550-f044624e2b47)
to this 
![Sneakers Online Shop Logo](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/138752385/49afe70c-b423-49f4-9e63-430098b52550)

**Comment by patelkiran185** [comment]
@harshalhonde21 please take a look at this

**Comment by harshalhonde21** [comment]
already there is logo in this website
