### ISSUE TITLE
Feat: sending email when user clicks on contact us form.

### ISSUE THREAD

**Issue by Samani-Humaira** [harshalhonde21/EcommerceSpectastyle#239]
### Describe the feature

Sending an email to the website owner when the "Contact Us" form is submitted ensures that they can easily get in touch with the user.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/142516438/64dfcfa5-9d85-4a94-bbb5-e0887638d2c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ARPITBAJPAI0098** [comment]
hello boss can you pls assign this issue to me i am having 1year of experience in Mern stack currently serving as the Technical Executive  of Sphnix largest techfest of Rajasthan under NIT jaipur

**Comment by harshalhonde21** [comment]
no need of this as the contact form is dummy
