### ISSUE TITLE
Feat:Footer

### ISSUE THREAD

**Issue by jennifereunice** [harshalhonde21/EcommerceSpectastyle#246]
### Describe the feature

can make the footer much attractive by alignment

### Add ScreenShots

![shooo](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/105411915/0a8aaa3e-24ea-4543-977e-dae3250f952b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no need as it is good not no update required
