### ISSUE TITLE
Feat:  Enhancing UI for links in Footer on hover

### ISSUE THREAD

**Issue by Madhu-mac** [harshalhonde21/EcommerceSpectastyle#247]
### Describe the feature

When we hover over the footer links we can see the cursor but the UI is the same we can add an underline to make the user experience better.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/88281761/f1cb5395-7e6b-4824-bd59-e8212632906f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rohit-yadavv** [comment]
iam working on this issue please assign it to me @harshalhonde21

**Comment by Madhu-mac** [comment]
> iam working on this issue please assign it to me @harshalhonde21

i'm already working on this issue. If it's assaigned to me under GSSoC i'll raise a PR for it

**Comment by harshalhonde21** [comment]
no need of this
