### ISSUE TITLE
Feat: Adding hover effect to the navbar-items

### ISSUE THREAD

**Issue by Madhu-mac** [harshalhonde21/EcommerceSpectastyle#248]
### Describe the feature

We need add hover effect to the navbar-items ( **cart & details icons** )

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/99901964/735ed71f-1402-410d-9509-a48a848d126f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rohit-yadavv** [comment]
iam working on this please assign it to me @harshalhonde21

**Comment by harshalhonde21** [comment]
the hovering effect is already there

**Comment by Madhu-mac** [comment]
@harshalhonde21 Bro there's no hover effect for cart and details icon, its has pointer only..
