### ISSUE TITLE
Feat: Add loading state

### ISSUE THREAD

**Issue by rohansen856** [harshalhonde21/EcommerceSpectastyle#251]
### Describe the feature

When the user tries to login, it takes time to process the request. In that time, there is no loading state, and the user can even try to sign in request again. I would like to add a loading state to improve the user interaction and also prevent users from doing a login request again, if one request is in progress already.
Please assign me this issue under gssoc'24

### Add ScreenShots

![Screenshot 2024-05-18 224720](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/108976786/000d0d77-646b-471a-8293-9652e78cdfbd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
great @rohansen856 you can work on it

**Comment by rohansen856** [comment]
I have closed this issue under PR #253. Thank you

**Comment by harshalhonde21** [comment]
great work @rohansen856

**Comment by rohansen856** [comment]
Happy to be of any help!
