### ISSUE TITLE
Fixing Product Ordering Page

### ISSUE THREAD

**Issue by Apurv7777** [harshalhonde21/EcommerceSpectastyle#255]
### Describe the feature

Fixes to be done 👍 :
1) Regularize the font size
2) Creating a dedicated product ordering page.
3) Changes in fonts.
4) Sometimes, the product photo is showing like below. Fixing it with default image.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/65327303/0b95ce93-4084-42a4-bb8d-d3d693a4738b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
No need of dedicated product descption page if you want to change the font family you can do that

**Comment by nishant0708** [comment]
assign me this issue under gssoc24
