### ISSUE TITLE
[Enhancement] making about page more attractive and better

### ISSUE THREAD

**Issue by shantam60** [harshalhonde21/EcommerceSpectastyle#260]
### Describe the feature

I want change the styling of the about page making it more appealing to customers.Current about page looks very boring. Assign me this issue under gssoc2024.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/129108528/a1a64d95-fe36-4ca2-9a9f-aa4f9d65f834)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no need of this
