### ISSUE TITLE
BUG: RESET PASSWORD and CHANGE PHOTO is not working

### ISSUE THREAD

**Issue by asthanegi14** [harshalhonde21/EcommerceSpectastyle#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the user profile section, only the logout button works properly Reset Password and Change Photo do not reflect any activity. Also, the UI of that page is quite disturbing, there is no margin between the username and reset password button. when I registered, I selected a profile picture but it didn't reflect in my profile after login.

![Screenshot (952)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/93486108/2c7f2810-cc71-4d58-a0ab-bd83878241d3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
you can work in this but this functionality should be correct in production also

**Comment by asthanegi14** [comment]
okay, sure

**Comment by asthanegi14** [comment]
Hey @harshalhonde21 can you add labels to this issue, it will help me.
