### ISSUE TITLE
Adding the 3d into the website

### ISSUE THREAD

**Issue by suraj-9849** [harshalhonde21/EcommerceSpectastyle#263]
### Describe the feature

So in the hero section by adding the 3d shoes which can move on the cursor hover this can attract the user.For this I will be using the spline and importing it into the website 

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/146669517/5f308b42-4f85-4639-b657-b501b5861d9c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not required as the website see more in functionality
