### ISSUE TITLE
Adding the automatic swiper in the swiper shoe section

### ISSUE THREAD

**Issue by suraj-9849** [harshalhonde21/EcommerceSpectastyle#264]
### Describe the feature

I just saw that the swiper which is present in the website doesnot have the autoplay feature so I thought of using the swiper.js for this and make it autoplay Can u please assign this to me under @GSSOC @harshalhonde21 

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/146669517/619eab32-a3d3-4bae-84f5-24908389ce17)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not required in this website
