### ISSUE TITLE
The logo in the responsive is not perfect

### ISSUE THREAD

**Issue by suraj-9849** [harshalhonde21/EcommerceSpectastyle#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/146669517/7a3c5ed9-f04e-4936-814a-63a57af2ea9d)
There is the issue in the text of the website when the website is made into responsive so I will fix it

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by harshalhonde21** [comment]
pull the code first it is change
