### ISSUE TITLE
Feat: Add Dark Mode and Light Mode Toggle

### ISSUE THREAD

**Issue by Hemashree21** [harshalhonde21/EcommerceSpectastyle#269]
### Describe the feature

I want to work on adding dark mode to the website so that users can toggle between light and dark mode.

@harshalhonde21 can you please assign this?

### Add ScreenShots

![Screenshot 2024-05-20 171836](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/138188163/b2e72acd-a662-4b90-8f34-fbb0cf847de6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
already  one issue is working on this
