### ISSUE TITLE
Feat:Dark mode

### ISSUE THREAD

**Issue by aryansharma220** [harshalhonde21/EcommerceSpectastyle#279]
### Describe the feature

We can add dark mode so that the website is soothing to eyes in low light conditions

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/133234867/95c8d25f-6341-4a08-ba09-25e617ebf2b2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
there is no need of dark mode as website should to aim colorfull
