### ISSUE TITLE
BUG:cross icon needs to be aligned properly in sidenav bar after click on hamburger. 

### ISSUE THREAD

**Issue by kapilG0** [harshalhonde21/EcommerceSpectastyle#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_20240522_131530](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/59639410/4d15922d-96bf-45ad-80be-cd8b0eb8f020)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @harshalhonde21 please assign this issue to me under gssoc 24

**Comment by harshalhonde21** [comment]
there is need to align the website also in mbl view as there is side screen bug and the whole logo in not come in side bar do with this all

**Comment by kapilG0** [comment]
> there is need to align the website also in mbl view as there is side screen bug and the whole logo in not come in side bar do with this all

Hello @harshalhonde21 yes i did that and raised pr https://github.com/harshalhonde21/EcommerceSpectastyle/pull/331. please check

**Comment by kapilG0** [comment]
Hello @harshalhonde21 i am closing this issue as pr #331 already merged.
Thanks
