### ISSUE TITLE
BUG: Alignment issue in the Product details section

### ISSUE THREAD

**Issue by Akash1965** [harshalhonde21/EcommerceSpectastyle#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# Description:
## Issue 1:
Within the dimensions `548x639` to `1150x639` the product details section is not centrally aligned due to which it's looking disproportioned.

## Issue 2:
In the product details card the elements are overflowing in case of smaller screens.

# Visuals:
## Issue 1:
<img width="1470" alt="Screenshot 2024-05-22 at 7 19 58 PM" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115504480/9452100d-a80d-4d29-b7da-c107d7325a26">

## Issue 2:
<img width="1470" alt="Screenshot 2024-05-23 at 12 47 30 AM" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115504480/4f75752c-0bdc-4e33-93bf-d98a6d121213">
<img width="1470" alt="Screenshot 2024-05-23 at 12 47 27 AM" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115504480/692f7055-dbb0-450c-b857-c5723a068414">
<img width="1470" alt="Screenshot 2024-05-23 at 12 47 24 AM" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115504480/a7a729ad-e53d-4be6-ab09-9063f0a2fab0">
<img width="1470" alt="Screenshot 2024-05-23 at 12 47 18 AM" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115504480/28625263-f7f7-44bb-b7bd-599a9ad7e4ee">

# Steps to Reproduce:
After setting up the project locally,
1. Click on the Products section
4. Then click on any of the product cards
5. Set the dimension between `548x639` to `1150x639`

# Expected Behavior:
## Issue 1:
<img width="1470" alt="Screenshot 2024-05-22 at 7 20 53 PM" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115504480/bccb4e10-2728-42fc-8aad-378968157fea">
## Issue 2:
<img width="1470" alt="Screenshot 2024-05-23 at 12 52 37 AM" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115504480/75979d31-5107-4bc6-bdd6-d84ec512695a">
<img width="1470" alt="Screenshot 2024-05-23 at 12 52 07 AM" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115504480/9725e4e2-ff75-4703-85e3-f79a030e6006">
<img width="1470" alt="Screenshot 2024-05-23 at 12 51 18 AM" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115504480/077a29f7-33f7-4825-8896-d4667c54e385">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akash1965** [comment]
@harshalhonde21 I would love to work on this issue. Please assign me this issue

**Comment by nishant0708** [comment]
hey please assign me this issue under gssoc24

**Comment by Akash1965** [comment]
@harshalhonde21 I would love to work on this issue. Can you please assign it to me

**Comment by harshalhonde21** [comment]
it is already solving by another one
