### ISSUE TITLE
Feat: Redesign the footer section and make a responsive footer section 

### ISSUE THREAD

**Issue by Surajkushwaha12** [harshalhonde21/EcommerceSpectastyle#293]
### Describe the feature

Hii This is Suraj Kushwaha . I am a gssoc Contributor . 
I am interested to work on the footer section . 
I am working on the footer redesign , add some content and make responsive footer .
so please assign me this task , I am very interested to work on this project.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/134843134/75191dcf-7637-4ff0-9b24-3bd676ece7d2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no need for footer as it is already done with what i want but you can make full responsive home page as there is some what bug

**Comment by Surajkushwaha12** [comment]
ok I will Make full responsive  homepage please assign me this task
