### ISSUE TITLE
Update and Improve Background Theme for Enhanced User Experience

### ISSUE THREAD

**Issue by skshrinaya** [harshalhonde21/EcommerceSpectastyle#294]
### Describe the feature

The current background theme of the e-commerce website lacks visual appeal, making it less engaging for users. The proposed solution involves implementing a new, vibrant color scheme and subtle textures to create a modern, attractive design. This update will ensure consistency across all pages, enhance responsiveness for various devices, and align with the brand's identity. By improving the background theme, we aim to increase user engagement, retention, and overall satisfaction with the website.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/125351066/258a1dd2-4a88-49b7-8b13-d284ec5c4ab9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by skshrinaya** [comment]
I am very eager in working on this issue . Please assign it to me.

**Comment by harshalhonde21** [comment]
no need to change the theme
