### ISSUE TITLE
Add Razorpay Payment Integration to E-Commerce Website

### ISSUE THREAD

**Issue by skshrinaya** [harshalhonde21/EcommerceSpectastyle#295]
### Describe the feature

Integrate Razorpay to provide a seamless and secure payment experience on the e-commerce website. This feature will enable users to make payments using various methods such as credit/debit cards, UPI, and net banking. The integration will enhance the user experience by offering a reliable and efficient checkout process. Additionally, it will support multiple currencies and provide real-time transaction updates, ensuring a smooth and trustworthy payment process for customers.

### Add ScreenShots

![WhatsApp Image 2024-05-23 at 10 27 46_53df8240](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/125351066/4affc613-b43f-409e-87cd-d413c4042827)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by skshrinaya** [comment]
Please assign this task to me . I want to work on this.

**Comment by harshalhonde21** [comment]
already stripe gateway is there then why to add razorpay??
