### ISSUE TITLE
BUG: Update Twitter Logo to 'X' in Footer Section

### ISSUE THREAD

**Issue by skshrinaya** [harshalhonde21/EcommerceSpectastyle#297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current footer section of the e-commerce website displays the old Twitter bird logo, which is outdated. To align with Twitter's rebranding, update the logo to the new 'X' design. This change will ensure that the website reflects the latest branding of Twitter, maintaining consistency and modernity. Updating the logo will enhance the website's visual appeal and ensure compliance with current social media branding standards.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by skshrinaya** [comment]
Please assign this task to me

**Comment by harshalhonde21** [comment]
already solving
