### ISSUE TITLE
Redesign About page

### ISSUE THREAD

**Issue by kashish-51** [harshalhonde21/EcommerceSpectastyle#302]
### Describe the feature

The about us page of this website is looking like a static html page. I want to make redesign this and make its UI/UX better.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/136115355/61f43737-edb8-405a-9209-ea65778ab31c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kashish-51** [comment]
@harshalhonde21 please assign this issue to me under GSSOC so that I can create some positive change in your website.

**Comment by Annu117** [comment]
@harshalhonde21 plz assign this to me under GSSOC'24.

**Comment by harshalhonde21** [comment]
no need of this as it is update and good to look
