### ISSUE TITLE
Fixing the backend and Frontend of review section

### ISSUE THREAD

**Issue by kashish-51** [harshalhonde21/EcommerceSpectastyle#303]
### Describe the feature

The review section of this website is not working as expected. After clicking on review button the following problem arises:
1) Review is not getting added properly
2) To show the review there must be a particular section below this description page.
3) Option to review through image is not available
4) Rating feature is also missing

Assign this issue to me under GSSOC so that I can work on all of these issues and fix them as soon as possible.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/136115355/681193d6-5936-4375-b04e-b00928dfc921)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
review is added there and it is see to admin and only top two review are showing to user no need as it is fixed as want to this application
