### ISSUE TITLE
Redesign UI/UX of profile section

### ISSUE THREAD

**Issue by kashish-51** [harshalhonde21/EcommerceSpectastyle#304]
### Describe the feature

The UI/UX of profile section is not appealing. There is no proper alignment and spacing between the buttons and text. Also when after clicking on Logout button it directly logs out user without asking for confirmation. I think these things needs to be fixed to make this website better.
So, @harshalhonde21 please assign this issue to me under GSSOC so that I can start contributing.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/136115355/d012c177-e7e2-4d57-9b3f-f183750a548f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
already doing in another issue
