### ISSUE TITLE
[Feat]: Implement Filter Options and Categories for Shoe Ordering WebsiteFeat:

### ISSUE THREAD

**Issue by Dhevamuthu** [harshalhonde21/EcommerceSpectastyle#308]
### Describe the feature

The feature involves implementing comprehensive filter options and organized product categories to enhance the usability of a shoe ordering website. Users will be able to filter products by price range, brand, customer ratings, size, and color, allowing them to quickly find items that meet their specific criteria. Additionally, the website will categorize products into main categories such as "Shoes" and "Slippers," with further subcategories like "Sports Shoes" and "Casual Slippers." This structured organization will make it easier for users to navigate the site and find exactly what they are looking for, improving the overall shopping experience.

### Add ScreenShots

![Screenshot 2024-05-24 141341](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123234572/f515233f-b3b3-425a-995f-6e96642ed9d4)
![Screenshot 2024-05-24 141418](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123234572/76650cc4-8357-49e7-ad4b-31e55712b1f0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey please assign me this issue under gssoc24

**Comment by harshalhonde21** [comment]
already done with this
