### ISSUE TITLE
Feat: Adding restrictions to phone number in contact form

### ISSUE THREAD

**Issue by kesharwaniyanshi** [harshalhonde21/EcommerceSpectastyle#310]
### Describe the feature

The phone number section accepts number of any length. We can add some restrictions to avoid spamming of messages with numbers of any length.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123561974/b21011d9-12c2-435b-8118-635dd51bffd4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by IIIT-n-HA** [comment]
### Can you assign me this issue under gssoc2024.

### Here is a sample code for it.

```
<form id="contactForm" action="#" method="POST">
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" required><br><br>
    
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required><br><br>
    
    <label for="phone">Phone:</label>
    <input type="tel" id="phone" name="phone" required maxlength="10"><br><br>
    
    <label for="message">Message:</label><br>
    <textarea id="message" name="message" rows="4" required></textarea><br><br>
    
    <button type="submit">Submit</button>
</form>
```

**Comment by harshalhonde21** [comment]
as it is dummy form so no need of this issue
