### ISSUE TITLE
BUG:Bad alignment of username

### ISSUE THREAD

**Issue by kesharwaniyanshi** [harshalhonde21/EcommerceSpectastyle#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Here Username overlaps email and reset password. It doesn't look nice and can be corrected .
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123561974/cfb88972-a17f-4925-8bc5-dd38e0b1f15a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by IIIT-n-HA** [comment]
### Can you assign me this issue under gssoc2024. I can improve the design.

**Comment by kesharwaniyanshi** [comment]
@harshalhonde21  please assign this issue to me.

**Comment by harshalhonde21** [comment]
why did you change the color of bg

**Comment by kesharwaniyanshi** [comment]
I did not change the color. My default setting is set to Dark mode so ig the change is due to that.

**Comment by kesharwaniyanshi** [comment]
can you assign the issue to me

**Comment by harshalhonde21** [comment]
It is updated see the website
