### ISSUE TITLE
Feat: Add confirmation for logout

### ISSUE THREAD

**Issue by kesharwaniyanshi** [harshalhonde21/EcommerceSpectastyle#312]
### Describe the feature

We can add a confirmation message before log out .It may happen user by mistake clicks logout ,So we can add a confirmation box on clicking logout .for better user experience

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123561974/0bc1b534-8bd9-415a-b4c4-7d1ae97c1ff6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
actually not required to solve this
