### ISSUE TITLE
Feature: the font styling is not much apealing

### ISSUE THREAD

**Issue by devagya-rattan** [harshalhonde21/EcommerceSpectastyle#315]
### Describe the feature

if we change the font for the website then it might look more appeling and satisfactory to the user

### Add ScreenShots

![Screenshot (137)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/112056749/7bb89520-e879-49cc-b577-c9ad1eecdda1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
the issue is already in process and done with this
