### ISSUE TITLE
BUG: No validation in Email Signup

### ISSUE THREAD

**Issue by Sailesh3000** [harshalhonde21/EcommerceSpectastyle#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am able to signup with incorrect email Please refer below
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/126142666/6513071e-d6cb-4940-9a3d-ef9dd5ab5174)
there is no validation to include .com,.in

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
the work is going in another issue
