### ISSUE TITLE
Feat: Add dynamic Copyright details section

### ISSUE THREAD

**Issue by Saimanjari777** [harshalhonde21/EcommerceSpectastyle#318]
### Describe the feature

The copyright details section is missing in this website. I would like to add the dynamic copyright details section which fetches the current year in the footer section.
Please assign this issue to me @harshalhonde21 

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/130165687/2bbd8200-6c0c-417b-9f5f-5beafa479e3f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
solve the issue in your past issue as it is very small contribute no need of two issue
