### ISSUE TITLE
Update a signup and signin  route with jwt authentication in backend and update the profile picture backend  

### ISSUE THREAD

**Issue by SAURABHVERMA00** [harshalhonde21/EcommerceSpectastyle#320]
Update the route of signin and sign up route withb jwt authentication and when we select the profile picture it not selected and it get error that not sign up this issue i will fix 
Please assign  me
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115395946/c343957e-d9b9-4426-a94a-b11409535a3b)

**Comment by harshalhonde21** [comment]
the issue is not in perfect form

closed for no read the repo guidelines first
