### ISSUE TITLE
Feat: Redux tooklit

### ISSUE THREAD

**Issue by Sid-80** [harshalhonde21/EcommerceSpectastyle#321]
### Describe the feature

I am willing to setup the redux toolkit for the state management across the application. 

### Add ScreenShots

Not required.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshikaSabharwal** [comment]
Hey @harshalhonde21
I can work on this isssue. Can you please add level label to this issue for gssoc.

**Comment by harshalhonde21** [comment]
issue not discribe correctly and no need of redux or redux toolkit as contextapi is already use
