### ISSUE TITLE
Feat: Navbar is not aligned good

### ISSUE THREAD

**Issue by prachita0504** [harshalhonde21/EcommerceSpectastyle#322]
### Describe the feature

 The button is not aligned correctly with the other elements in the navbar, which affects the visual consistency and user experience of the website.

### Add ScreenShots

![Screenshot 2024-05-26 130001](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/139040702/794e5a38-98c3-47f1-90a6-7c6d8b92e76d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sneha0019** [comment]
I can solve the navbar issue as I already have worked on the same project. Please assign in to me

**Comment by harshalhonde21** [comment]
already working on this
