### ISSUE TITLE
Update Signup and Signin Routes with JWT Authentication and Profile Picture Update in Backend

### ISSUE THREAD

**Issue by SAURABHVERMA00** [harshalhonde21/EcommerceSpectastyle#324]
## Description:
The current signup and signin routes lack JWT authentication, and users are unable to successfully upload profile pictures during registration. This issue affects the user experience by preventing successful account creation and profile picture uploads.

When a user attempts to upload a profile picture during the signup process, an error occurs, indicating that the profile picture was not selected. This results in users being unable to complete the signup process.

## Visuals:
![Screenshot 2024-05-26 192520](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115395946/a9205472-05ff-4063-bd9f-b54aebaa99ff)

## Steps to Reproduce:
Go to the signup page.
Fill in the necessary details (e.g., username, password, etc.).
Attempt to upload a profile picture.
Submit the signup form

## Expected Behavior:
Users should be able to sign up and sign in with JWT authentication.
The profile picture should be successfully uploaded and saved during the signup process.

## Actual Behavior:
Users encounter an error stating that the profile picture was not selected, preventing successful signup.

## Priority and Labels:
Priority: High
Labels: bug, authentication, file-upload 

Please assign this issue to me as I am eager to work on resolving it.

**Comment by aryan-1309** [comment]
Please Assign this to me, i want to work on this.

**Comment by ShampaShaw** [comment]
Please Assign this to me, i want to work on this.

**Comment by VanshikaSabharwal** [comment]
Hey @harshalhonde21
I can work on this isssue. Can you please add level label to this issue for gssoc.

**Comment by harshalhonde21** [comment]
already have the feature
