### ISSUE TITLE
BUG:spacing improve 

### ISSUE THREAD

**Issue by aashkaaaaaa** [harshalhonde21/EcommerceSpectastyle#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/138461600/00c6fc81-8556-4e68-9f7f-4a0a5f127f1e)
there's one small improvement that is needed.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no explain the issue correct where issue or bug it and not tell about the page therefore the issue is closed
