### ISSUE TITLE
(GSSoC'24) Fixing Layout and Add Functionality to Profile Page After Login

### ISSUE THREAD

**Issue by Apurv7777** [harshalhonde21/EcommerceSpectastyle#33]
It is good to fix the profile dashboard.
I can also add the functionality to change the profile picture . Also , update it to the backend.

**Comment by adarsh-jha-dev** [comment]
Hey @Apurv7777 , will it be ok if i start working on this?

**Comment by harshalhonde21** [comment]
Great you can do that but i want correct MVC model work as you see in the Repo

**Comment by harshalhonde21** [comment]
> Hey @Apurv7777 , will it be ok if i start working on this?

What are your approach

**Comment by Apurv7777** [comment]
1. **Model:**
I will create a profile pic url field for the user profile in MongoDB.
2. **Controller:**
Then, I will create routes and controllers to handle profile picture uploads and updates.
3. **View:**
Then, I will show on profile page using React.

**Comment by Apurv7777** [comment]
Do assign a level to this.

**Comment by Apurv7777** [comment]
### Work Update : 
1) Changed the way of input of profile picture on Signup.
2) User can see the uploaded image.
3) The image is stored in base64 format in mongodb.

### Work to be done:
1) Adding functionality of changing profile photo.
2) Adding upload icon to indicate user to upload image.

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/65327303/9373b409-e977-430a-adb5-6e678fda8619)
