### ISSUE TITLE
BUG: UI design is not looking goof

### ISSUE THREAD

**Issue by dhruv8433** [harshalhonde21/EcommerceSpectastyle#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@harshalhonde21 

check this out

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/114583978/44d2bb60-030d-453a-b44c-27dc2e92a1f2)

we can improve ui design something like this,
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/114583978/d8c56337-45de-4d66-b045-e447071ed5b9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
actually the UI is shows about messy design because i want that not this great design
