### ISSUE TITLE
BUG:remove extra space

### ISSUE THREAD

**Issue by Varsani2520** [harshalhonde21/EcommerceSpectastyle#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in responsive device display lots off spaces ,it is look like not a good for users 
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/137641079/d3491725-20f0-4d8a-8cfe-6fe2bec6c47c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aryan-1309** [comment]
i can fix this, please assign this to me.

**Comment by harshalhonde21** [comment]
done with this issue
