### ISSUE TITLE
Feat: Adding Legal Pages to the website

### ISSUE THREAD

**Issue by Hemashree21** [harshalhonde21/EcommerceSpectastyle#336]
### Describe the feature

I want to work on adding the legal pages which are cookie policy, terms and conditions and licensing pages. I will make sure that the pages are responsive as well.

@harshalhonde21 can you please assign this to me?

### Add ScreenShots

![Screenshot 2024-05-23 164724](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/138188163/b7d9afe4-049c-4557-806e-1e5c1c46e9b9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshikaSabharwal** [comment]
Hey @harshalhonde21
I can work on this isssue. Can you please add level label to this issue for gssoc.

**Comment by Hemashree21** [comment]
@harshalhonde21 can you please add the labels and assign it to me so that I can start working on the issue?

**Comment by harshalhonde21** [comment]
doesn't need for now try another issue
