### ISSUE TITLE
Feat: Adding FAQ section

### ISSUE THREAD

**Issue by Hemashree21** [harshalhonde21/EcommerceSpectastyle#337]
### Describe the feature

I want to work on adding the FAQ section so that users can resolve any questions they have about the website.

@harshalhonde21 can you please assign this to me?

### Add ScreenShots

![Screenshot 2024-05-24 212548](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/138188163/7aadbbc2-c019-4829-a898-f9f4f9389589)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
you can add
