### ISSUE TITLE
DOC: how to commit - create new branch

### ISSUE THREAD

**Issue by Annu117** [harshalhonde21/EcommerceSpectastyle#339]
### What's wrong with the existing documentation

Missing commit commands.
For multiple issues, commit. Participants can create new branches. Remove conflict for committing in the previous branch.
Will add the right way to commit.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
do with this @Annu117
