### ISSUE TITLE
BUG: Arrow button is not clickable

### ISSUE THREAD

**Issue by m3kvt** [harshalhonde21/EcommerceSpectastyle#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The arrow is not clickable. I wish to add a reference to the arrow so that on clicking the user gets navigated to the next page.

If you have any suggestions on where to navigate, kindly inform me.

https://github.com/harshalhonde21/EcommerceSpectastyle/assets/98379619/274222aa-8acc-4754-a0b6-ac47d3d81be3

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
actually it is showing that go down no need of down clickable
