### ISSUE TITLE
Feat:Enhancing "ABOUT US"  page 

### ISSUE THREAD

**Issue by swetha5157** [harshalhonde21/EcommerceSpectastyle#343]
### Describe the feature

**Description:**
* The About Us page serves as an important aspect of any website as it transcends the company's history, performance, zenith, and so on.
* Hence it is essential to make it sophisticated with user experience 
*  I will enhance the design and UI of the ABOUT US page

### Add ScreenShots

![Screenshot 2024-05-29 121859](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123291594/103f01eb-72b5-4a1f-be8f-af4684b88b3f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
great @swetha5157

**Comment by swetha5157** [comment]
Thankyou @harshalhonde21 for assigning the issue
