### ISSUE TITLE
BUG:Lack of Authorization in Contact form

### ISSUE THREAD

**Issue by Dhevamuthu** [harshalhonde21/EcommerceSpectastyle#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have encountered a security and functionality issue within the application related to the authentication of email addresses entered in the contact form. Specifically, after logging in with my email ID and name, I observed that when I enter a different name and email ID in the contact form, the application does not verify whether this email ID matches my logged-in email ID. This lack of validation allows me to submit the contact form with any email address, irrespective of the email ID I used to log in.

This flaw poses significant security risks and undermines the integrity of the application. Users could potentially misuse this loophole to submit forms with unauthorized email addresses, leading to possible impersonation or the submission of false information. It is crucial that the application implements proper validation to ensure that the email ID entered in the contact form matches the authenticated email ID of the logged-in user. This measure would enhance the application's security and ensure the accuracy and authenticity of the information being submitted.

I recommend that this issue be addressed promptly to prevent any potential misuse and to uphold the integrity of the user data within the application.

https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123234572/33cb9885-d752-4b32-b235-3774301725ea

the below is the entered mail id and username.
![Screenshot 2024-05-29 141023](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123234572/2de19237-677c-4de1-9760-16e045758aaf)

Please assign gssoc and level label to it assign the issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
actually the contact form is dummy so no need of this functionality
