### ISSUE TITLE
Seamless Navigation Between Signup, Login, and Home Pages

### ISSUE THREAD

**Issue by ShampaShaw** [harshalhonde21/EcommerceSpectastyle#347]
### Describe the feature

In the current web application, users often find the transition between the signup, login, and home pages to be unintuitive or cumbersome. To enhance the user experience, we need to implement a seamless navigation flow. 

After clicking the "Signup" button and successfully creating an account, the user is automatically redirected to the login page.
After logging in with valid credentials, the user is redirected to the home page instead of the dashboard.

### Add ScreenShots

![gssoc](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115999821/0624f4a3-69c7-459d-ae4b-1d989fb8b0e1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShampaShaw** [comment]
assign me this issue 
under gssoc'24

**Comment by harshalhonde21** [comment]
no need of this as register/ signup the user is success auth with server
