### ISSUE TITLE
better UI/UX

### ISSUE THREAD

**Issue by 777advait** [harshalhonde21/EcommerceSpectastyle#35]
the overall look of the website can be made to look more professional and eye catching by switching fonts and colors

**Comment by harshalhonde21** [comment]
what are your approach for this explain??

**Comment by 777advait** [comment]
> what are your approach for this explain??

the current layout and font on the website looks quite cluttered which can be easily improvised by implementing proper CSS positioning and fonts.

kindly assign me this issue!

**Comment by harshalhonde21** [comment]
updated the issue already solve
