### ISSUE TITLE
adding framer motion

### ISSUE THREAD

**Issue by powerstone666** [harshalhonde21/EcommerceSpectastyle#350]
### Describe the feature

using framer motion we'll be implementing a scroll bar feature along with many animation divs for text and images. include in level 2

### Add ScreenShots

framer motion scroll bar will be priority along with other animated divsa 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no need as website is official not personal or anything
