### ISSUE TITLE
adding a counter in totall user visited

### ISSUE THREAD

**Issue by powerstone666** [harshalhonde21/EcommerceSpectastyle#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

adding a counter to go from 0 to total users visited on reload.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
already have at the website
