### ISSUE TITLE
Feat: Adding a review section in the product details.

### ISSUE THREAD

**Issue by Chandan-6** [harshalhonde21/EcommerceSpectastyle#354]
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### Describe the feature

By adding a review section, we aim to enhance the overall shopping experience on our platform, increase customer engagement, and build trust through transparent product feedback.

### Add ScreenShots

![Screenshot 2024-06-02 074403](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/141998868/e5b5286e-f103-4fbe-ac06-2235f958bae4)

**Comment by harshalhonde21** [comment]
already preseent
