### ISSUE TITLE
Feat: Adding Forgot password feature

### ISSUE THREAD

**Issue by Chandan-6** [harshalhonde21/EcommerceSpectastyle#355]
### Describe the feature

The forgot password will make the users to reset their passwords, if they haven't stored or forgot.
This prevents the users from loosing the account.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/141998868/e18b691f-e9d7-4320-9d3b-755caab201b4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no need becuase had change password functionality
