### ISSUE TITLE
BUG: Monthly update part issue

### ISSUE THREAD

**Issue by ayush-848** [harshalhonde21/EcommerceSpectastyle#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If no email is provided and if we click on the monthly update button, no alert for enter your email pops up

I want to add this, so that if box is empty and button is pressed then an alert type "Please, Enter your email" appears if nothing is provided.
If "abcd" is provervied, then alert will appear "Incorrect email"

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@harshalhonde21 please assign this issue to me

**Comment by harshalhonde21** [comment]
as it is dummy no need of any update
