### ISSUE TITLE
Add Scroll Down Functionality for Arrow Button

### ISSUE THREAD

**Issue by RahulRudra81** [harshalhonde21/EcommerceSpectastyle#360]
### Describe the feature

I'd like to request a feature enhancement for the project. Currently, the website lacks a scroll-down functionality when clicking on an arrow button. Implementing this feature would improve user navigation and provide a smoother user experience.

Feature Details:

Objective: Enhance user experience by enabling smooth scrolling to the next section when an arrow button is clicked.
Expected Behavior: When a user clicks the arrow button, the page should automatically scroll down to the next section.
Implementation Suggestions:
Use JavaScript/jQuery for smooth scroll functionality.
Ensure the arrow button is visually distinct and intuitive for users.
Test the functionality across different browsers and devices to ensure compatibility.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/91683510/754d1f2e-41de-4d37-8fa0-d06dca1becd6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
actually no need of scroll down functionality because user should see all project and for need there is scrool up button
