### ISSUE TITLE
BUG:Add hover text to the social media icons

### ISSUE THREAD

**Issue by AkhilaSunesh** [harshalhonde21/EcommerceSpectastyle#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/140897461/1f520e5c-29fc-4f9f-8c76-f58bca1d3e37)
Add hover text to the social media icons

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
already have no need of there any thing
