### ISSUE TITLE
Adding the Like Button To the Product 

### ISSUE THREAD

**Issue by narayani9120** [harshalhonde21/EcommerceSpectastyle#364]
### Describe the feature

Adding a like button to the product will enhance the website by allowing users to express and their preferences. Users will benefit from more personalized content and recommendations, improving their shopping experience and satisfaction with the website.

### Add ScreenShots

![Screenshot 2024-06-03 181837](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/125353066/25bce6c5-2acb-46fb-8c9e-4bf07b76a6e2)

 Expected :
![Screenshot 2024-06-03 183236](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/125353066/e665f266-0177-49a3-ade2-1cbbc4b9aec0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not neccessary as done the comment option is done
