### ISSUE TITLE
BUG: Adding Responsiveness to the Homepage or About page and Updating the navbar for small devices

### ISSUE THREAD

**Issue by asthanegi14** [harshalhonde21/EcommerceSpectastyle#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The responsiveness of the homepage and About page is disturbed.
![Screenshot (975)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/93486108/350d1b05-79c9-4b18-8e85-4fa0fb137117)

![Screenshot (976)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/93486108/9a7e3518-ceb9-42ee-9225-c91f75501f12)

Also, the navbar in small devices should be closed after clicking on the homepage, about page, or any other button. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by asthanegi14** [comment]
Hey @harshalhonde21 , I would like to work on this issue.

**Comment by harshalhonde21** [comment]
great work on this as it is more necessary and listen check whole website where where the bug of responsivness is there and do changes
