### ISSUE TITLE
BUG: On successful sigup or login user should be naviagted to home page.

### ISSUE THREAD

**Issue by mohit-bhandari45** [harshalhonde21/EcommerceSpectastyle#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

So, after signingup user is navigated to login, and after that to profile. Instead user should navigate to Home page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
Not necessary as after login the user should show the profile the home page is already seen without login
