### ISSUE TITLE
BUG: content should come inside card

### ISSUE THREAD

**Issue by kapilG0** [harshalhonde21/EcommerceSpectastyle#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_20240604_163511](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/59639410/5766308b-e3be-448e-9094-623a51b4de3e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @harshalhonde21 please assign this issue to me under gssoc 24

**Comment by harshalhonde21** [comment]
the issue is solved
