### ISSUE TITLE
Responsiveness issue: navbar

### ISSUE THREAD

**Issue by Godcoder696** [harshalhonde21/EcommerceSpectastyle#37]
Navbar is not responsive for (width: 1001px - 1170px)

**Comment by adarsh-jha-dev** [comment]
Hey @Godcoder696 , could you please assign this issue to me? I'd like to work on it.

**Comment by harshalhonde21** [comment]
See the readme file of repo and create the issue proper as readme file says

**Comment by Harshitazz** [comment]
I can do this. please assign me.

**Comment by RohanGlitched** [comment]
@harshalhonde21 I would love to resolve this issue.
Can you please assign me this issue.
