### ISSUE TITLE
Feat:after click on icon comes in sidenav sidenav should close

### ISSUE THREAD

**Issue by kapilG0** [harshalhonde21/EcommerceSpectastyle#370]
### Describe the feature

![Screenshot_20240604_163657](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/59639410/038fe165-da9e-4ff1-9426-d4d9f48f5a49)
As you can see after click on link I have to close from above cross icon which should not done

### Add ScreenShots

![Screenshot_20240604_163657](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/59639410/699a2a23-d0ce-4791-ae25-3a3288815f66)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @harshalhonde21 please assign this issue to me under gssoc 24

**Comment by harshalhonde21** [comment]
the functionality is already done
