### ISSUE TITLE
Feat:Enhancing the Website Footer for Better Appeal and Interactivity

### ISSUE THREAD

**Issue by nirajsingh015** [harshalhonde21/EcommerceSpectastyle#378]
### Describe the feature

As part of my GSSoC contribution, I want to update the website footer to make it more appealing and interactive. By organizing content properly, adding interactive elements, and applying effective design techniques, I aim to create a footer that not only provides essential information but also enhances user engagement and experience.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115022991/c66593d7-d83e-4683-a979-71f96cf74699)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
as far its great no need of change
