### ISSUE TITLE
BUG: Contact form on submitting does not display any message

### ISSUE THREAD

**Issue by Varsha010101** [harshalhonde21/EcommerceSpectastyle#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After a user submits the contact form the page refreshes. There is no message whether it is submitted or not. This issue is to add a message of success above the form.
![Screenshot 2024-06-05 204908](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/142898488/4b500402-eecb-4cfe-a888-4acbbae90a9b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
acually it is dummy form so need of this is not neccesary
