### ISSUE TITLE
Product Category Menu

### ISSUE THREAD

**Issue by Godcoder696** [harshalhonde21/EcommerceSpectastyle#38]
Adding category menu (shoe, T-shirt, skirt, watch, etc) might be useful for overall user experience rather than a simple search bar for everything

**Comment by harshalhonde21** [comment]
See the readme file of repo and create the issue proper as readme file says

**Comment by RohanGlitched** [comment]
@harshalhonde21 I would love to resolve this issue.
Can you please assign me this issue.
