### ISSUE TITLE
Feat: Custom Cursor

### ISSUE THREAD

**Issue by chaanakyaaM** [harshalhonde21/EcommerceSpectastyle#380]
### Describe the feature

The website is awesome, but it can be even more attractive and professional if there is a custom cursor which syncs with the website design.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/131477601/a4e6bd54-1cae-474f-b545-f21fad85de4a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
great work on it @chaanakyaaM
