### ISSUE TITLE
Feat: Redesign the entire website

### ISSUE THREAD

**Issue by heyprathamgoyal** [harshalhonde21/EcommerceSpectastyle#381]
### Describe the feature

will add transitions, hovers, animations, etc to redesign the website and make it more interactive

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/135994674/cda282f5-48f8-447c-873f-15aa75f7a216)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no need to do this so far its look good
