### ISSUE TITLE
Feat: improve the about us section

### ISSUE THREAD

**Issue by AbhishiktaRay03** [harshalhonde21/EcommerceSpectastyle#383]
### Describe the feature

Better alignment of cards giving professional look to the website.

### Add ScreenShots

![Uploading image.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
as about is already updated and looks good no need so far
