### ISSUE TITLE
Feat: Glowing cursor all in the screen  (3d effect)

### ISSUE THREAD

**Issue by namandude** [harshalhonde21/EcommerceSpectastyle#387]
### Describe the feature

Hey I want to add more 3d effect in the website as i want to add the cursor in the screen when ever user moves the mouse the beautifull effects generated all in the screen where ever mouse moves .
I will add the user experience in another level.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/118013565/daec40d3-3abd-44db-a945-367eb926f0aa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
already done in website
