### ISSUE TITLE
Feat: Add more fields to signup

### ISSUE THREAD

**Issue by chandannekya** [harshalhonde21/EcommerceSpectastyle#389]
### Describe the feature

Enhance the user registration form by adding additional fields to capture more detailed user information. The new fields will include
FirstName, LastName, Gender and optional filed of address that can be edited in profile section

### Add ScreenShots

![Screenshot 2024-06-08 095046](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/121476456/c2c57122-5a52-4ba2-92dc-5d37c65e25d9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not actually neccessary
