### ISSUE TITLE
Add filter

### ISSUE THREAD

**Issue by pallavidhakne** [harshalhonde21/EcommerceSpectastyle#39]
for further enhance the user experience on the SpectaStyle website, consider integrating filters for price (allowing sorting from low to high and vice versa), brands, and sizes

**Comment by harshalhonde21** [comment]
See the readme file of repo and create the issue proper as readme file says

**Comment by Prateek579** [comment]
@harshalhonde21 I would love to resolve this issue.
Can you please assign me this issue.

**Comment by harshalhonde21** [comment]
use correct format of issue making
