### ISSUE TITLE
Feat:Creating LOGO for the website

### ISSUE THREAD

**Issue by aartijangra** [harshalhonde21/EcommerceSpectastyle#399]
### Describe the feature

I was going through the website and found that there is no logo for the website. So i want to create LOGO for spectastyle.
Please assign me this issue @harshalhonde21.

### Add ScreenShots

![Screenshot 2024-06-11 093810](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/143300846/08841c30-6f22-4040-9cf2-06946dbdee0f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
great do work on it @aartijangra
