### ISSUE TITLE
Implement User Authentication, Wishlist, and Shopping Cart Functionality

### ISSUE THREAD

**Issue by pallavidhakne** [harshalhonde21/EcommerceSpectastyle#40]
The current version of the SpectaStyle website lacks user authentication, a wishlist component, and a shopping cart ("the bucket"). These features are crucial for personalizing the user experience

**Comment by harshalhonde21** [comment]
See the readme file of repo and create the issue proper as readme file says

**Comment by tusharyadav11** [comment]
would like to work on this functionality. in my earlier projects i have worked on this functionality. I would be grateful if you could assign me this functionality

@harshalhonde21

**Comment by Shruti-Sawant** [comment]
Currently wishlist  icon  is not added and Add to wishlist button is also not added on every products , reset password is also not working. Please assign this issue to me under GSSoc24
