### ISSUE TITLE
BUG: Add "Confirm Password" Field to Signup Page

### ISSUE THREAD

**Issue by chandannekya** [harshalhonde21/EcommerceSpectastyle#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, our application lacks a "Confirm Password" field on the signup page, which can lead to users accidentally entering incorrect passwords and experiencing frustration when they are unable to log in. Implementing a "Confirm Password" field will enhance user experience by ensuring that users enter their desired password correctly during registration.
![Screenshot 2024-06-11 215252](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/121476456/d5885952-b65f-4ff2-be9c-4c40391b01c9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Raushan0300** [comment]
I fixed this issue and raising a PR

**Comment by harshalhonde21** [comment]
no need
