### ISSUE TITLE
Feat: Add Privacy Policy and Terms and Conditions Pages to Website

### ISSUE THREAD

**Issue by MastanSayyad** [harshalhonde21/EcommerceSpectastyle#404]
### Describe the feature

Hey @harshalhonde21 

I would like to add legal pages such as privacy policy and terms and conditions for the website to make it look more professional and to maintain the guidelines 

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/101971980/f4df27f9-0913-4815-abdf-7ba0df453180)

Could you pls assign this issue to me under GSSOC?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MastanSayyad** [comment]
please take a look at this issue @harshalhonde21

**Comment by harshalhonde21** [comment]
actually its not necessary to do so you can work on another issue therefore this issue has been closed
