### ISSUE TITLE
add copyright and hover the footer of the text

### ISSUE THREAD

**Issue by jayanththalla** [harshalhonde21/EcommerceSpectastyle#405]
### Describe the feature

In the footer, there is no copyright and no hover effect on the text.we can add the other social media links like github and discord
please assign @harshalhonde21 
please label gssoc and add level 

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/121346142/c8dcf5c0-2188-4e8b-b4d7-19c8189675d8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not neccessary
