### ISSUE TITLE
Feat: Automatically Comment on Issue Raise

### ISSUE THREAD

**Issue by thevijayshankersharma** [harshalhonde21/EcommerceSpectastyle#407]
### Describe the feature

I propose implementing a feature that automatically comments on an issue when it is raised. This comment will serve as an acknowledgment to the contributor for bringing the issue to our attention and provide any necessary guidance or next steps.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
great what are your approach to do this so

**Comment by thevijayshankersharma** [comment]
There will be a workflow folder in .github, in it I will write the code in.yml format to make that possible.

**Comment by harshalhonde21** [comment]
@thevijayshankersharma  great can continue
