### ISSUE TITLE
Feat: Adding a testimonials section.

### ISSUE THREAD

**Issue by nagalakshmi08** [harshalhonde21/EcommerceSpectastyle#408]
### Describe the feature

The Testimonials consists of user reviews which says how good the website is, and also how they got benefitted from it.
Below attached image is my previous work on testimonials.
Please assign me this issue, I would like to contribute to this project under GSSoC'24.

### Add ScreenShots

![338464852-9affe838-a6a7-4cd4-b94d-f4bbf5ccd239](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/121669832/c57e48b5-5317-4d20-9aca-336da466ca62)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
great do with this @nagalakshmi08
