### ISSUE TITLE
BUG:Nav bar not responsive 

### ISSUE THREAD

**Issue by parikhitritgithub** [harshalhonde21/EcommerceSpectastyle#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in mobile view navbar not responsive 
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/124444610/022d795d-8dac-4665-b39f-f2a2adc1e1ee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
great do this

**Comment by kratik1237** [comment]
I am interested in this issue, please assign me.
@harshalhonde21

**Comment by parikhitritgithub** [comment]
i will merge it  by tomorrow
