### ISSUE TITLE
BUG: Cursor appearning on links and cards

### ISSUE THREAD

**Issue by chaanakyaaM** [harshalhonde21/EcommerceSpectastyle#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![WhatsApp Image 2024-06-13 at 7 42 32 AM](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/131477601/90e351a8-b06a-45c0-b509-c552bdc3023d)

![WhatsApp Image 2024-06-13 at 7 42 32 AM (1)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/131477601/7db85289-9478-4feb-bf38-b13369b6d766)

(sorry about the images, i couldn't take the screenshot of the cursor)

BUG: When ever the cursor is hovering over any link or product card the cursor(pointer) is appearing, this makes the website a buggy feeling.
I would like to fix this bug as well as add links hover effects to footer links.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
its default behaviour
