### ISSUE TITLE
BUG:In footer section ,links are not working.

### ISSUE THREAD

**Issue by PrachiJadhav2310** [harshalhonde21/EcommerceSpectastyle#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the footer section,links are not working. After clicking on those links they should redirect to particular page or website section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no need as it is dummy
