### ISSUE TITLE
Feat:Adding Google Auth 

### ISSUE THREAD

**Issue by mukilan2815** [harshalhonde21/EcommerceSpectastyle#417]
### Describe the feature

We can add google auth for the login and register so that users can easily signup using one click.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/71129858/6ae0cfb2-02ce-4d34-9ba0-17359f2495b9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no need of this actually
