### ISSUE TITLE
update middleware.js

### ISSUE THREAD

**Issue by NirbheekKumar** [harshalhonde21/EcommerceSpectastyle#420]
Token Extraction:

Ensure the token is extracted correctly from the Authorization header. Typically, tokens are prefixed with Bearer. The split(' ')[1] extracts the actual token part.
If the Authorization header doesn't follow the expected format, the code handles it gracefully.

Error Handling:

Consistent response format for both missing and invalid tokens.
Specific handling for TokenExpiredError and a catch-all for other JWT-related errors.

**Comment by harshalhonde21** [comment]
issue not write as mention in repo
