### ISSUE TITLE
Feat: Adding react-toastify to contact form

### ISSUE THREAD

**Issue by Varshi45** [harshalhonde21/EcommerceSpectastyle#422]
### Describe the feature

In the contact section, the current contact form does not indicate anything if the mail is submitted or not. So whenever a user submits the contact form, adding React-Toastify to say the form is submitted or not.

### Add ScreenShots

**Before Submission**
![Screenshot 2024-06-16 183925](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/116535984/ff3ba51b-0313-4dac-8338-4613302430fb)
**After Submission**
![Screenshot 2024-06-16 183950](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/116535984/cbb157f0-8c6c-42b8-94d8-8630d00edd0a)
![Screenshot 2024-06-16 183937](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/116535984/b0542fb5-0bcb-412e-96c0-5e19601100a9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not required as already it is
