### ISSUE TITLE
Feat: Add email sending functionality for 'Get Updates' button

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [harshalhonde21/EcommerceSpectastyle#426]
### Describe the feature

Implement an email sending functionality triggered when users click the 'Get Updates' button. This feature will send email acknowledging and appreciation on subscription. This feature aims to enhance user experience by promptly sending message via email and also adding alert to inform that the button is clicked. This functionality using either EmailJS or Nodemailer.

### Add ScreenShots

![gssoc24](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/128472306/fed6f1dd-8845-4dc9-87dc-2fbee420fd62)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not required as it is dummy
