### ISSUE TITLE
BUG: Unable to see cursor on the product details component

### ISSUE THREAD

**Issue by the-code-artist** [harshalhonde21/EcommerceSpectastyle#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am unable to see cursor on the specific product details component which is making it difficult to navigate using cursor

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
done already
