### ISSUE TITLE
BUG: Logo goes outside in responsive screen

### ISSUE THREAD

**Issue by dhruv8433** [harshalhonde21/EcommerceSpectastyle#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@harshalhonde21 

check this out,

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/114583978/570ddb9c-4456-430e-b6e9-b09b8f6f2790)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
fix it great @dhruv8433

**Comment by dhruv8433** [comment]
Thank you @harshalhonde21
