### ISSUE TITLE
Feat: Review US Section

### ISSUE THREAD

**Issue by Damini2004** [harshalhonde21/EcommerceSpectastyle#433]
### Describe the feature

Helps us to know the better user experience review.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/119414762/5fac0d0d-276b-408d-9c2e-d977c14778cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
already in the website just to the research what is and not in website
