### ISSUE TITLE
Feat: Add Product Ratings 

### ISSUE THREAD

**Issue by VaishnaviMankala19** [harshalhonde21/EcommerceSpectastyle#434]
### Describe the feature

I want to incorporate product ratings into the product card.

### Add ScreenShots

![Screenshot (38)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/131646799/eb0fa475-73f1-4373-ab86-1a47cc6f229b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no need as of this
