### ISSUE TITLE
Feat: adding email input validation in the form

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [harshalhonde21/EcommerceSpectastyle#437]
### Describe the feature

adding email input validation in the form

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/125277258/6c92de21-df1e-4683-814c-69030c79a52f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no need as it is dummy
