### ISSUE TITLE
Google authentication  using firebase 

### ISSUE THREAD

**Issue by naisargi17** [harshalhonde21/EcommerceSpectastyle#444]
### Describe the feature

Through firebase ,Google authentication can be enhance .I already had worked on it . If you want I can do it . Please assign me under gssoc'24.

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/111778403/fc2607fa-2138-43ab-95ee-788f522b6e51)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not required
