### ISSUE TITLE
Feat: Improve UI of filters at product page 

### ISSUE THREAD

**Issue by rohit-yadavv** [harshalhonde21/EcommerceSpectastyle#445]
### Describe the feature

want to improve filters ui to make them more appealing to user

### Add ScreenShots

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/126584837/249b0d12-2277-4ec1-95f4-d7ca554e6894)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
great @rohit-yadavv

**Comment by harshalhonde21** [comment]
as your previous issue is very small and this too you need to do all 2 in same PR to get level1

**Comment by rohit-yadavv** [comment]
Ok
