### ISSUE TITLE
BUG: Cursor not visible in navbar

### ISSUE THREAD

**Issue by rohit-yadavv** [harshalhonde21/EcommerceSpectastyle#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/126584837/d8f399cd-2acf-4dd4-b2d6-cee9591e2b09)

cursor is below navbar which makes it difficult to see 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
you can work on it @rohit-yadavv
