### ISSUE TITLE
 Feat: Wish to store the details of user in firebase

### ISSUE THREAD

**Issue by sheetal-81** [harshalhonde21/EcommerceSpectastyle#448]
### Describe the feature

I want to add the database part , so whenever user add their credentials in login and signup form then their detail will be saved in firebase 

### Add ScreenShots

I will add the firebase so it stores the user credentials

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
no need as already storing in mongodb db
