### ISSUE TITLE
Feat:Wish to ennhance the what user say about us 

### ISSUE THREAD

**Issue by sheetal-81** [harshalhonde21/EcommerceSpectastyle#450]
### Describe the feature

i want to make the what users say about us section by giving some border modification and shape of it 

### Add ScreenShots

in rounded rectangle shape 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not required
