### ISSUE TITLE
improve the product card

### ISSUE THREAD

**Issue by Harshitazz** [harshalhonde21/EcommerceSpectastyle#46]
**improve the style for cards **

![Screenshot 2024-05-10  #203708](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/118474653/74be6d13-41f1-40c6-91eb-2b169470863f)

please permit me to change .

**Comment by shrutib11** [comment]
I can improve the style of product cards. please assign this issue to me

**Comment by harshalhonde21** [comment]
what are your approach give some sample design first

**Comment by Harshitazz** [comment]
> what are your approach give some sample design first

somewhat like this. will make a reusable react component according to the theme.
![Screenshot 2024-05-10 211534](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/118474653/a57c06d7-0fdd-45f6-a79c-cb66ea7095f4)

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@harshalhonde21

**Comment by Harshitazz** [comment]
@harshalhonde21 assign it to me

**Comment by harshalhonde21** [comment]
No need of this as this is already updated in one PR
