### ISSUE TITLE
cart and profile are not visible on homepage

### ISSUE THREAD

**Issue by Yashgabani845** [harshalhonde21/EcommerceSpectastyle#47]
whenever we visit website there is no direct navigation to cart and profile they are hidden because of wrong margin
![Screenshot (25)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/127788321/3d8bd2f0-7529-4503-97e0-df62b73b7b3e)

 can we make them visible so that user interaction could be improvised
 
![Screenshot (23)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/127788321/40878d93-0505-4c03-ae9a-f3d6de6e8561)

**Comment by Yashgabani845** [comment]
please assign this issue to me i will make sure it should be visible at size

**Comment by harshalhonde21** [comment]
go ahead

**Comment by officeneerajsaini** [comment]
i think this issue not longer anymore .
