### ISSUE TITLE
BUG: Design a new Photo for a Homepage 

### ISSUE THREAD

**Issue by DevGajjar28** [harshalhonde21/EcommerceSpectastyle#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey i want to add a new Designed image for a home page. Current image do not look good and quality of a image not matching the background.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not neccessary
