### ISSUE TITLE
Feat: Hidden Price Tag

### ISSUE THREAD

**Issue by divyansh-2005** [harshalhonde21/EcommerceSpectastyle#482]
### Describe the feature

To every Product Card we should make a additional <div> that have Price wriiten in it and initially it should be hidden and whenever the user hovers over the card then the div should be visible along with the price tag.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not neccessary
