### ISSUE TITLE
Feat:In the product section we can add a shine effect when hovered 

### ISSUE THREAD

**Issue by Riddhi162** [harshalhonde21/EcommerceSpectastyle#487]
### Describe the feature

So when a particular product is hovered we can give this shine effect to make UI look more better

### Add ScreenShots

Uploading Shine image on hover pure CSS animation - Google Chrome 2024-07-20 12-26-35 (online-video-cutter.com).mp4…

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not neccessary
