### ISSUE TITLE
Feat:Improve the UI of add to cart sections.

### ISSUE THREAD

**Issue by Riddhi162** [harshalhonde21/EcommerceSpectastyle#488]
### Describe the feature

The items in the card of the products in add to cart looks very scattered the shape of image and everything is just not in place and it looks a bit awkward i can improe that.The price is somewhere else the font is too big etc

### Add ScreenShots

![image](https://github.com/user-attachments/assets/354b3803-5635-46cf-a647-40a38eb46a2b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not neccessary
