### ISSUE TITLE
Feat: In the offers section remove the gradient background from behind and clip it inside the text

### ISSUE THREAD

**Issue by Riddhi162** [harshalhonde21/EcommerceSpectastyle#489]
### Describe the feature

Rather then the gradient having the moving background i can clip it inside the text of OFFERS  that woyuld look better since in your page there is no where a title that has a background.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/cadf4f43-49ce-43f7-9a7c-472323cd2f1b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not neccessary and it is like what i want
