### ISSUE TITLE
BUG:The close button when the product card is opened is not aligned perfectly

### ISSUE THREAD

**Issue by Riddhi162** [harshalhonde21/EcommerceSpectastyle#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The close button should be a bit on the right and not come on top of the inside card its size can be reduced and it can be given some animation when it is clicked.
![image](https://github.com/user-attachments/assets/02d88731-5d7b-46f3-9cf0-bbe28452ed84)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not neccessary
