### ISSUE TITLE
Feat: Create a new section to show the number of user visits, number of products bought, achievements etc in the home page

### ISSUE THREAD

**Issue by Riddhi162** [harshalhonde21/EcommerceSpectastyle#493]
### Describe the feature

User visits can be removed from the navbar and a new section can be created where we can put all the numbers and rather than static the numbers load when someone comes in that viewport. We can also add indias first website in center and alll other numbers around

### Add ScreenShots

![image](https://github.com/user-attachments/assets/39c7d27a-f740-453d-8a42-e9e137d3a07a)
something like this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not neccessary
