### ISSUE TITLE
Feat: In the about section we can add glowing and moving borders to the divs in the about section

### ISSUE THREAD

**Issue by Riddhi162** [harshalhonde21/EcommerceSpectastyle#494]
### Describe the feature

The about section UI can be made more better if we add the moving and glowing borders to the divs

### Add ScreenShots

https://github.com/user-attachments/assets/e6a21871-a9e7-46e4-9dd9-5786261a5eef

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
not neccessary
