### ISSUE TITLE
Feat "Enhance the Trail Effect" and "Hide" in Mobile View

### ISSUE THREAD

**Issue by MastanSayyad** [harshalhonde21/EcommerceSpectastyle#496]
### Describe the feature

Hey @harshalhonde21 

I would like to enhance the current cursor trail effect to look more interactive and engaging, 

- the current one looks like a dot, instead, I will add multiple circles in it which will reduce their size gradually and follow the movement of the cursor, 
- the color would be radial gradient little transparent to look more alive 

also I think we should **hide the trail effect in mobile view** as we didn't need any cursor there instead we touch on the screens on the mobile, due to the trail effect it is causing bugs in mobile view such as sticking to the screen when touched!

### Add ScreenShots

https://github.com/user-attachments/assets/0556e746-884f-4077-afad-5784cce5cd07

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshalhonde21** [comment]
assigned @MastanSayyad
