### ISSUE TITLE
Feat: Add Legal Information to Footer

### ISSUE THREAD

**Issue by lovelymahor** [harshalhonde21/EcommerceSpectastyle#497]
### Describe the feature

Our website currently lacks essential legal information in the footer, which is necessary for transparency and compliance with legal standards.

### Add ScreenShots

![Screenshot (248)](https://github.com/user-attachments/assets/711c3a50-d950-4ee1-a3bb-8fd37a94f713)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lovelymahor** [comment]
@harshalhonde21 Please assign it to me I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by harshalhonde21** [comment]
dont really need
