### ISSUE TITLE
"Unable to Reset Password and Update Profile Picture After Signing Up"

### ISSUE THREAD

**Issue by Manan024** [harshalhonde21/EcommerceSpectastyle#50]
### **Issues** 
After signing up on the website, users encounter issues with resetting their password and updating their profile image. When attempting to reset the password, the system fails to send the reset email, and updating the profile picture feature does not function as expected. This issue obstructs users from accessing essential account management functionalities, impacting user experience and site usability.

### **Solving the Issues**
We will create an reset password flow through which user can reset password easily and will use multer for updating profile photo

### **Screenshots**
![Screenshot 2024-05-10 211041](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/148992830/7135fd21-8276-40f2-bdea-868d650a2e2b)
![Screenshot 2024-05-10 211029](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/148992830/5339f4e0-a93e-483a-bfe0-aa42e3ae145c)

**Comment by Manan024** [comment]
Hey @harshalhonde21  Would be great if you assign me the task so that I can make the changes Asap :) !

Looking forward to a positive response. (GSSOC'24)

**Comment by tusharyadav11** [comment]
would like to work on this functionality. in my earlier projects i have worked on this functionality. I would be grateful if you could assign me this functionality

@harshalhonde21
