### ISSUE TITLE
Give a default user profile picture

### ISSUE THREAD

**Issue by aryansharma220** [harshalhonde21/EcommerceSpectastyle#51]
Description:
When user tries to sign up it asks for a profile picture, but users should be allowed to continue without a profile picture and we should provide a default profile picture.

Uploading SPECTASTYLE and 5 more pages - Personal - Microsoft_ Edge 2024-05-10 21-20-53.mp4…

Steps to Reproduce:
We can provide a default image as profile picture if user doesn't add one.

@harshalhonde21  Please assign it to me so that I can start working

**Comment by Harshitazz** [comment]
i can do this assign this to me
