### ISSUE TITLE
Implement forgot password

### ISSUE THREAD

**Issue by Niharika0104** [harshalhonde21/EcommerceSpectastyle#53]
#### Description:
The application currently lacks the "Forgot Password" feature, which is crucial for user account recovery. This issue is to implement the necessary pages and functionality required for the "Forgot Password" feature.

#### Tasks:
1. **Create Forgot Password Page:** Develop a new page or modal for the "Forgot Password" functionality.
   - **Steps to Implement:**
     1. Design the user interface for entering email addresses for password reset requests.
     2. Implement the frontend components for the Forgot Password page/modal.
   - **Expected Behavior:** Users should be able to access the Forgot Password page/modal to initiate the password reset process.

2. **Backend Logic for Password Reset:** Develop backend logic to handle password reset requests and send reset instructions to the user's email.
   - **Steps to Implement:**
     1. Define API endpoints or backend routes to handle password reset requests.
     2. Implement logic to generate and store password reset tokens securely.
     3. Integrate with email services to send password reset instructions to users.
   - **Expected Behavior:** Upon submitting a password reset request, users should receive instructions on how to reset their passwords via email.

**Comment by SumitKumar-17** [comment]
@harshalhonde21 I want to work on this issue. Can you assign this issue to me under GSSoc'24?

**Comment by tusharyadav11** [comment]
would like to work on this functionality. in my earlier projects i have worked on this functionality. I would be grateful if you could assign me this functionality

**Comment by Niharika0104** [comment]
@SumitKumar-17 @tusharyadav11  Can you please look at other issues? I made similar kind of open source contribution in other repository.

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@harshalhonde21

**Comment by harshalhonde21** [comment]
closed because it will email auth

**Comment by Niharika0104** [comment]
@harshalhonde21 How will it do email auth.I think we need forget password coz user will enter the email id and password if the password is not matching and if he forgot the password then we should provide an option to reset the password that is what every website out there does.
