### ISSUE TITLE
Wishlist Integration Across All Products

### ISSUE THREAD

**Issue by Niharika0104** [harshalhonde21/EcommerceSpectastyle#56]
#### Description:
We propose integrating wishlist functionality across all products, enabling users to conveniently save and revisit desired items. This enhancement aims to elevate user experience by providing seamless item tracking and fostering engagement. Below are the tasks required to implement this feature:

#### Tasks:
1. **Create Wishlist UI Components:** Develop UI components to allow users to add items to their wishlist and view/manage their wishlist.
   - **Steps to Implement:**
     1. Design the UI elements for adding items to the wishlist and viewing/managing the wishlist.
     2. Implement frontend components for adding items to the wishlist and displaying wishlist items.
   - **Expected Behavior:** Users should be able to add products to their wishlist and view/manage their wishlist seamlessly.

2. **Backend Logic for Wishlist Management:** Develop backend logic to handle wishlist functionality, including adding/removing items from the wishlist and retrieving wishlist data.
   - **Steps to Implement:**
     1. Define API endpoints or backend routes for managing wishlist operations.
     2. Implement logic to add/remove items to/from the wishlist and retrieve wishlist data for users.
   - **Expected Behavior:** Backend should support CRUD operations for wishlist items and provide necessary data to frontend for wishlist management.

3. **Integrate Wishlist Functionality Across Product Pages:** Modify product pages to include options for adding products to the wishlist.
   - **Steps to Implement:**
     1. Update product page UI to include a button or option for adding products to the wishlist.
     2. Integrate frontend functionality to add/remove products to/from the wishlist directly from product pages.
   - **Expected Behavior:** Users should be able to add/remove products to/from their wishlist directly from product pages.

**Comment by harshalhonde21** [comment]
Just read the readme how the issue is creating is all written in that

**Comment by harshalhonde21** [comment]
Issue removed as not created as guidlines
