### ISSUE TITLE
Navbar Button showing disoriented borders

### ISSUE THREAD

**Issue by Akash1965** [harshalhonde21/EcommerceSpectastyle#60]
## Issue:
When the window size is 693 x 440 px, the profile and shopping cart buttons have disoriented black borders surrounding them. This issue is faced when these buttons are hovered upon.
 
## Visuals:

<img width="730" alt="Screenshot 2024-05-10 at 10 39 23 PM" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115504480/1604dd9c-2928-4b5d-ab7a-d157dca9cc9b">

<img width="730" alt="Screenshot 2024-05-10 at 10 39 26 PM" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/115504480/a7480528-808a-4f3b-b18d-31ed38fcfd28">

## Steps to Reproduce:

- Make the browser window dimensions 693 x 440 px
- Hover on the profile or the shopping cart buttons on the navbar

## Expected Behavior:
The black border should be removed so that the UI becomes better

**Comment by Akash1965** [comment]
@harshalhonde21 i would love to fix this issue.
Can you please assign me this issue so that i can fix it.

**Comment by Yashgabani845** [comment]
it has been solved in issue #47  you can check and close this issue

**Comment by Akash1965** [comment]
Oh my bad.....Sorry for the inconvenience
