### ISSUE TITLE
fixing the product layout and adding hover animation

### ISSUE THREAD

**Issue by agxmbedi** [harshalhonde21/EcommerceSpectastyle#64]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!
![Uploading Screenshot 2024-05-10 at 11.10.42 PM.png…]()

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@harshalhonde21

**Comment by harshalhonde21** [comment]
come up with proper issue
