### ISSUE TITLE
[bug] Footer Link Not Responsive 

### ISSUE THREAD

**Issue by Manav173** [harshalhonde21/EcommerceSpectastyle#66]
Problem:
The navigation menu on our website currently includes links to pages titled "About Us," "Products," and "Contact Us". However, In the footer these links are not correctly configured to lead users to the corresponding pages, resulting in a poor user experience.

Solution:
Update the footer links to accurately direct users to the respective pages.

I would be really thankful if you assign me this issue as a part of GSSoC'24 @harshalhonde21 .

**Comment by Anup2601** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'24 @harshalhonde21 .

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@harshalhonde21

**Comment by Tushtiadlakha** [comment]
Please assign this issue to me under GSSoC'24 @Tushtiadlakha

**Comment by aditya7483thakur** [comment]
Hello Sir ! Please assign me this issue under GSSOC 24

**Comment by samikshapandagle** [comment]
Hello @harshalhonde21 please assign me this issue under gssco'24 I would like to contribute my skills on ths issue

**Comment by harshalhonde21** [comment]
@Manav173  great issue contribute and come up with great documentated PR
