### ISSUE TITLE
[Bug] Missing Review Page

### ISSUE THREAD

**Issue by Manav173** [harshalhonde21/EcommerceSpectastyle#67]
Problem:
Currently, the website lacks a dedicated space for users to provide feedback or report any issues they encounter while using the platform.

Solution:
Implement a review page which will serve as a centralized hub for collecting user feedback, enabling us to enhance the user experience and resolve any issues efficiently.

I would be really thankful if you assign me this issue as a part of GSSoC'24 @harshalhonde21 .

**Comment by Anup2601** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'24.

**Comment by harshalhonde21** [comment]
go with the issue and feature template

**Comment by Manav173** [comment]
Shall I proceed with the task @harshalhonde21 .
