### ISSUE TITLE
UI: Horizontal Scrollbar

### ISSUE THREAD

**Issue by rohit-yadavv** [harshalhonde21/EcommerceSpectastyle#73]
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/126584837/da0f9cb6-0b8d-409d-8c21-e1477a2206b0)
horizontal scrollbar is visible in whole site degrading overall ui experience

**Comment by MohitGoyal09** [comment]
hey, pls assign to me i can fix this

**Comment by harshalhonde21** [comment]
conflits in code
