### ISSUE TITLE
change photo feature is not working 

### ISSUE THREAD

**Issue by Yashgabani845** [harshalhonde21/EcommerceSpectastyle#77]
### **Issue :**
inside our profile page there is a feature called change profile photo,  when we click on it there is no response 

### **Expected :** 
when we click on that button file input should be taken and new uploaded photo should be updated in database as well as profile page photo 

### **Currently on clicking change photo**
![Screenshot (36)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/127788321/fc579c3c-a79c-40bb-9af9-c475b131841d)

### **what is expected** 

![Screenshot (39)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/127788321/0c8b3134-d2e8-431f-bcb1-abc760cbc031)

### **and after uploading view :**

![Screenshot (40)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/127788321/e9660879-08a5-4e6a-bd77-14c242747799)

**Comment by Yashgabani845** [comment]
please assign me this issue i will make sure about this feature along with database update

**Comment by Apurv7777** [comment]
I am working on that .

**Comment by Yashgabani845** [comment]
may be we could propose more design idea , perfect MVC model according repo.

**Comment by abhiperfect** [comment]
Subject: Issue Report: Change Photo Feature Not Functioning

Hi  @harshalhonde21  ,

I hope you're doing well. I wanted to bring to your attention an issue encountered with the change photo feature on your platform—it appears to be malfunctioning.

As someone who's familiar with your code, I'm keen to investigate and resolve this issue promptly to ensure smooth functionality for our users.

Could we discuss this further and perhaps allocate some time to troubleshoot and fix the problem?


Best regards,
Abhishek

**Comment by harshalhonde21** [comment]
Wrong format of issue
