### ISSUE TITLE
Conditional Navbar rendering+Icons enhancement

### ISSUE THREAD

**Issue by Abhinavpatra** [harshalhonde21/EcommerceSpectastyle#80]
## Description

- I want to make the navbar a conditionally rendering component, such that it appears only when the screen is being scrolled down or when still: enhancing the look of the site
- I can enhance the icon size by 1.2x on hovering them, it kindof just looks better.
- also the hover change on some of the nav and other elements gets a bit dark, instead of a cleaner simpler look.

## Conclusion
Let me know if you can assign me this issue, i have already done the icon and hover change, only the nav edit is left in my personal codespace. Thank you

**Comment by Abhinavpatra** [comment]
hey @harshalhonde21 let me know if you can assign me this issue

**Comment by harshalhonde21** [comment]
Take the pull first and hovering of navbar is done and first updated not required
