### ISSUE TITLE
UI improvement of About Section

### ISSUE THREAD

**Issue by Mandakini-S** [harshalhonde21/EcommerceSpectastyle#81]
Issue:
The About section's user interface requires improvement, and the content lacks proper organization.
Solution:
UI can be made visually appealing and easy to read.
Screenshot:
![Screenshot 2024-05-11 125517](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/85100316/12878cae-a88a-4cc1-b77c-eaa60d2e451e)

**Comment by Mandakini-S** [comment]
I want to work on this issue. Can you please assign it to me , @harshalhonde21 ?

**Comment by Yashgabani845** [comment]
it is affecting navbar 
i have already worked on navbar 
i can make UI of about and contact page 
such that both pages would be more readbale and other components does not affect it 
please assign me this issue 
![Screenshot (41)](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/127788321/26e3575f-6d1b-470f-bc8f-91b60e1ca3c7)
this could be better UI of about page

**Comment by MehtabAsHellic** [comment]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by AshishKumarSamantaray** [comment]
I have a design ready in a figma file please assign me for recreating this design which will be interactive as well.

**Comment by harshalhonde21** [comment]
get the pull first
