### ISSUE TITLE
Landing page isnt responsive

### ISSUE THREAD

**Issue by Ankitapanda25** [harshalhonde21/EcommerceSpectastyle#83]
The landing page lacks responsiveness in desktop view merging into other divs

<img width="1070" alt="image" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123666302/5991624d-a838-4ea3-82de-d787164a2af8">

Please assign me this so that i can work on it under GSSOC'24

**Comment by Harshitazz** [comment]
assign it to me
