### ISSUE TITLE
[BUG] Nav items UI fix

### ISSUE THREAD

**Issue by Ankitapanda25** [harshalhonde21/EcommerceSpectastyle#84]
<img width="1069" alt="image" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123666302/26596cee-5060-4ba8-affb-70e6b70c9d45">

The nav items ui needs to fixed, it doesnt look appropriate to the color theme. Please assign me this so that i can work on it under GSSOC'24

**Comment by harshalhonde21** [comment]
done with this not need of this update
