### ISSUE TITLE
(GSSoC'24) Logo Clickable Area Issue: Text Cursor and Ineffective Redirect

### ISSUE THREAD

**Issue by Apurv7777** [harshalhonde21/EcommerceSpectastyle#9]
Hey there,

I noticed a minor but impactful issue with the logo on your app's website. Currently, when users hover over the logo, it displays a text cursor instead of a pointer, and it doesn't redirect to the homepage when clicked.

**Steps to Reproduce:**
1) Visit the homepage of the website.
2) Hover over the logo in the header.

**Expected Behavior:**
The cursor should change to a pointer indicating clickability. Clicking on the logo should redirect the user to the homepage.

**Actual Behavior:**
The cursor remains as a text cursor. Clicking on the logo doesn't redirect the user.

This small fix could enhance user experience and streamline navigation. I'd be happy to contribute to resolving this issue as an open-source contribution.

Looking forward to your feedback.

Best regards,
Apurv Panchal

**Comment by harshalhonde21** [comment]
Basically I have give the route of Home directly, and I dont want the behaviour of logo clickable
