### ISSUE TITLE
issue to display placeholder is not properly.

### ISSUE THREAD

**Issue by krinalsuthar** [harshalhonde21/EcommerceSpectastyle#90]
@harshalhonde21 I can find one issue that is to fix the placeholder in the your message input box see in the below image
 
![issue](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/141125453/c7f9c6b0-9fdf-4692-ad07-141a867c60d4)

I AM WORKING UNDER GSSOC'24 PLEASE ASSIGN THIS TASK TO ME.

**Comment by harshalhonde21** [comment]
Take the pull always the issue is already solve
