### ISSUE TITLE
Adding 'Confirm Password' Option to Signup Page.

### ISSUE THREAD

**Issue by Naman197** [harshalhonde21/EcommerceSpectastyle#91]
Hey @harshalhonde21 ,I'm willing to contribute to this project for GSSoC24. I noticed that there's no "confirm password" field on the signup page, which could improve user experience and security.Could you please assign me this issue? I'm eager to work on it.

**Comment by AmrutaZagade** [comment]
Hey @harshalhonde21 ,I'm willing to contribute to this project for GSSoC24. Could you please assign me this issue? I'm eager to work on it.

**Comment by Sumkaur02** [comment]
@harshalhonde21, Kindly assign this task to me under Gssoc24. I will prioritize this enhancement to elevate platform performance and user satisfaction.

**Comment by harshalhonde21** [comment]
no need of this in website
