### ISSUE TITLE
Redirect to Mail on clicking Email id

### ISSUE THREAD

**Issue by Faraaz22** [harshalhonde21/EcommerceSpectastyle#92]
- Description :  The email Id in the footer is just test text, it would be better if we convert it into a link which will redirect directly to mail.

<img width="379" alt="image" src="https://github.com/harshalhonde21/EcommerceSpectastyle/assets/130041060/de17acde-4b12-4577-be02-b58904f3a0e9">

- Steps to Reproduce : not including href tag is the cause

- Expected Behavior: A pop up should come on clicking the email ID asking the choice of your email app, on selecting any one it should redirect to making a draft in that app 

Kindly assign this issue to me under Gssoc24.

**Comment by Shashi8637** [comment]
Hey @harshalhonde21 ,I'm willing to contribute to this project for GSSoC24. Could you please assign me this issue? I'm eager to work on it.

**Comment by IshikaBrar21** [comment]
please assign this issue to me for GSSoC'24

**Comment by abhiperfect** [comment]
Subject: Implementation of Email Redirection on Clicking Email ID

Hi @harshalhonde21  ,

I hope this message finds you well. I've noticed that on our website, clicking on email IDs doesn't redirect users to their default email client. I believe implementing this feature could improve user experience and encourage more interactions via email.

I'm interested in working on this issue and exploring how we can seamlessly redirect users to their email clients when they click on email IDs across our platform.

Best regards,
Abhsiehk
