### ISSUE TITLE
User experience issue in login/signup

### ISSUE THREAD

**Issue by Adeesh-bode** [harshalhonde21/EcommerceSpectastyle#94]
Your website allows exploration before login/signup. However, when a user adds a product to the cart and is then asked to log in or sign up, it should redirect the user back to the product page they were viewing, or at least add that product to the cart.

**Comment by harshalhonde21** [comment]
give with the whole description and video and take pull first or take video of live website

**Comment by harshalhonde21** [comment]
Close because no response
