### ISSUE TITLE
Redirect to call, mail application on clicking them in contact us and footer.

### ISSUE THREAD

**Issue by Rajput-xv** [harshalhonde21/EcommerceSpectastyle#96]
Hey @harshalhonde21, 
i would like to add feature to Mobile Number, Gmail where they are available on clicking them it will redirect user to specific application to proceed further.
So, assign this to me.

**Comment by kajolchatt** [comment]
Hi @harshalhonde21 I'd like to work on this issue. Would you please assign this to me?

**Comment by harshalhonde21** [comment]
give detail description with visually

**Comment by Rajput-xv** [comment]
Few more additions 
1. Redirect on clicking the logo of website. 
2. Adjustment in your message section in contact form under contact page.
3. Add some indication in navbar for user to identify the current/active page.

**Comment by harshalhonde21** [comment]
go with this but always while you will update code in local get the pull first

**Comment by Rajput-xv** [comment]
> give detail description with visually


https://github.com/harshalhonde21/EcommerceSpectastyle/assets/114978813/10238cc6-d301-43ed-8975-a73a2e64ec34


https://github.com/harshalhonde21/EcommerceSpectastyle/assets/114978813/2c8ff004-d471-4951-9e17-10b6d6d014e7



you can see in this for sample i made.
i can't share full due to personal information will display.

**Comment by Rajput-xv** [comment]
> go with this but always while you will update code in local get the pull first

Sure!!

**Comment by abhiperfect** [comment]
Subject: Enhancement Proposal: Redirect to Call or Email Application on Clicking Contact Info

Hi @harshalhonde21  ,

I trust this message finds you well. I've noticed an opportunity to improve user experience on our platform by enabling direct redirection to call or email applications when users click on contact information, especially in the "Contact Us" section and footer.

Given my familiarity with your codebase, I believe I can swiftly implement this enhancement to streamline user interactions.

I'm eager to collaborate on this project and discuss the best approach to integrate this functionality seamlessly into our platform.


Best regards,
Abhishek
